import type { Language } from './landing-i18n';

export type AnalysisApiKey =
  | 'subscriptionUnavailable' | 'auditUnavailable' | 'freeUnavailable' | 'signInGet'
  | 'invalidId' | 'readAnalysis' | 'notFound' | 'invalidPage' | 'historyUnavailable' | 'quotaUnavailable'
  | 'origin' | 'sessionExpired' | 'filename' | 'requestId' | 'market' | 'invalidFile'
  | 'checkImport' | 'saveAnalysis';

type Copy = Record<AnalysisApiKey, string>;
const es: Copy = {
  subscriptionUnavailable:'La suscripción no está disponible. Comprueba la configuración de pagos.',
  auditUnavailable:'La auditoría histórica no está disponible.',
  freeUnavailable:'La prueba gratuita no está disponible. Comprueba la configuración de cuota por cuenta.',
  signInGet:'Inicia sesión para consultar tus análisis.', invalidId:'Identificador no válido.',
  readAnalysis:'No se puede leer el análisis. Comprueba la configuración de la base de datos.', notFound:'Análisis no encontrado.',
  invalidPage:'Página no válida.', historyUnavailable:'El historial no está disponible. Comprueba la configuración de la base de datos.', quotaUnavailable:'La cuota no está disponible.',
  origin:'Origen de solicitud no permitido.', sessionExpired:'Tu sesión ha caducado. Vuelve a entrar.', filename:'El nombre de archivo debe tener entre 1 y 120 caracteres.',
  requestId:'Identificador de importación no válido.', market:'Europa es el mercado operativo en esta fase. Los siguientes mercados se activarán después de validar sus reglas.',
  invalidFile:'Archivo no válido.', checkImport:'No se ha podido comprobar la importación. Vuelve a intentarlo.',
  saveAnalysis:'No se ha podido guardar el análisis. No se ha confirmado ningún guardado; revisa la conexión y vuelve a intentarlo.',
};
export const analysisApiCopy: Record<Language, Copy> = {
  es,
  en:{...es,subscriptionUnavailable:'Subscription data is unavailable. Check the payment configuration.',auditUnavailable:'Historical audit data is unavailable.',freeUnavailable:'The free trial is unavailable. Check the per-account quota configuration.',signInGet:'Sign in to view your analyses.',invalidId:'Invalid identifier.',readAnalysis:'The analysis cannot be read. Check the database configuration.',notFound:'Analysis not found.',invalidPage:'Invalid page.',historyUnavailable:'History is unavailable. Check the database configuration.',quotaUnavailable:'Quota information is unavailable.',origin:'Request origin is not allowed.',sessionExpired:'Your session has expired. Sign in again.',filename:'The file name must contain between 1 and 120 characters.',requestId:'Invalid import identifier.',market:'Europe is the active market at this stage. Additional markets will be enabled after their rules are validated.',invalidFile:'Invalid file.',checkImport:'The import could not be verified. Try again.',saveAnalysis:'The analysis could not be saved. No save has been confirmed; check your connection and try again.'},
  fr:{...es,subscriptionUnavailable:'Les données d’abonnement sont indisponibles. Vérifiez la configuration des paiements.',auditUnavailable:'Les données de l’audit historique sont indisponibles.',freeUnavailable:'L’essai gratuit est indisponible. Vérifiez la configuration du quota par compte.',signInGet:'Connectez-vous pour consulter vos analyses.',invalidId:'Identifiant non valide.',readAnalysis:'Impossible de lire l’analyse. Vérifiez la configuration de la base de données.',notFound:'Analyse introuvable.',invalidPage:'Page non valide.',historyUnavailable:'L’historique est indisponible. Vérifiez la configuration de la base de données.',quotaUnavailable:'Le quota est indisponible.',origin:'Origine de la requête non autorisée.',sessionExpired:'Votre session a expiré. Reconnectez-vous.',filename:'Le nom du fichier doit contenir entre 1 et 120 caractères.',requestId:'Identifiant d’import non valide.',market:'L’Europe est le marché actif à ce stade. Les autres marchés seront activés après validation de leurs règles.',invalidFile:'Fichier non valide.',checkImport:'Impossible de vérifier l’import. Réessayez.',saveAnalysis:'Impossible d’enregistrer l’analyse. Aucun enregistrement n’a été confirmé ; vérifiez votre connexion et réessayez.'},
  de:{...es,subscriptionUnavailable:'Abonnementdaten sind nicht verfügbar. Prüfen Sie die Zahlungskonfiguration.',auditUnavailable:'Historische Auditdaten sind nicht verfügbar.',freeUnavailable:'Die kostenlose Testversion ist nicht verfügbar. Prüfen Sie die Kontingentkonfiguration pro Konto.',signInGet:'Melden Sie sich an, um Ihre Analysen anzuzeigen.',invalidId:'Ungültige Kennung.',readAnalysis:'Die Analyse kann nicht gelesen werden. Prüfen Sie die Datenbankkonfiguration.',notFound:'Analyse nicht gefunden.',invalidPage:'Ungültige Seite.',historyUnavailable:'Der Verlauf ist nicht verfügbar. Prüfen Sie die Datenbankkonfiguration.',quotaUnavailable:'Kontingentinformationen sind nicht verfügbar.',origin:'Anfrageursprung ist nicht zulässig.',sessionExpired:'Ihre Sitzung ist abgelaufen. Melden Sie sich erneut an.',filename:'Der Dateiname muss zwischen 1 und 120 Zeichen enthalten.',requestId:'Ungültige Importkennung.',market:'Europa ist derzeit der aktive Markt. Weitere Märkte werden nach Validierung ihrer Regeln freigeschaltet.',invalidFile:'Ungültige Datei.',checkImport:'Der Import konnte nicht geprüft werden. Versuchen Sie es erneut.',saveAnalysis:'Die Analyse konnte nicht gespeichert werden. Es wurde keine Speicherung bestätigt; prüfen Sie Ihre Verbindung und versuchen Sie es erneut.'},
  it:{...es,subscriptionUnavailable:'I dati dell’abbonamento non sono disponibili. Controlla la configurazione dei pagamenti.',auditUnavailable:'I dati dell’audit storico non sono disponibili.',freeUnavailable:'La prova gratuita non è disponibile. Controlla la configurazione della quota per account.',signInGet:'Accedi per consultare le tue analisi.',invalidId:'Identificatore non valido.',readAnalysis:'Impossibile leggere l’analisi. Controlla la configurazione del database.',notFound:'Analisi non trovata.',invalidPage:'Pagina non valida.',historyUnavailable:'La cronologia non è disponibile. Controlla la configurazione del database.',quotaUnavailable:'Le informazioni sulla quota non sono disponibili.',origin:'Origine della richiesta non consentita.',sessionExpired:'La sessione è scaduta. Accedi di nuovo.',filename:'Il nome del file deve contenere da 1 a 120 caratteri.',requestId:'Identificatore di importazione non valido.',market:'L’Europa è il mercato attivo in questa fase. Gli altri mercati verranno attivati dopo la validazione delle relative regole.',invalidFile:'File non valido.',checkImport:'Impossibile verificare l’importazione. Riprova.',saveAnalysis:'Impossibile salvare l’analisi. Nessun salvataggio è stato confermato; controlla la connessione e riprova.'},
  pt:{...es,subscriptionUnavailable:'Os dados da subscrição não estão disponíveis. Verifique a configuração dos pagamentos.',auditUnavailable:'Os dados da auditoria histórica não estão disponíveis.',freeUnavailable:'O teste gratuito não está disponível. Verifique a configuração da quota por conta.',signInGet:'Inicie sessão para consultar as suas análises.',invalidId:'Identificador inválido.',readAnalysis:'Não é possível ler a análise. Verifique a configuração da base de dados.',notFound:'Análise não encontrada.',invalidPage:'Página inválida.',historyUnavailable:'O histórico não está disponível. Verifique a configuração da base de dados.',quotaUnavailable:'A informação de quota não está disponível.',origin:'Origem do pedido não permitida.',sessionExpired:'A sua sessão expirou. Inicie sessão novamente.',filename:'O nome do ficheiro deve ter entre 1 e 120 caracteres.',requestId:'Identificador de importação inválido.',market:'A Europa é o mercado ativo nesta fase. Os restantes mercados serão ativados após validação das respetivas regras.',invalidFile:'Ficheiro inválido.',checkImport:'Não foi possível verificar a importação. Tente novamente.',saveAnalysis:'Não foi possível guardar a análise. Nenhuma gravação foi confirmada; verifique a ligação e tente novamente.'},
};

export function analysisApiText(language: Language, key: AnalysisApiKey): string { return analysisApiCopy[language][key]; }
