import type { Language } from './landing-i18n';

export type BillingMessageKey = 'origin'|'signInCheckout'|'signInPortal'|'onlyUnlimited'|'legalNotReady'|'invalidRequest'|'subscriptionRead'|'paymentPrepare'|'siteUrl'|'stripePrice'|'stripePage'|'paymentOpen'|'noSubscription'|'portalOpen';

type Copy = Record<BillingMessageKey,string>;
const es: Copy = {
  origin:'Origen de solicitud no permitido.',signInCheckout:'Inicia sesión para contratar Unlimited.',signInPortal:'Inicia sesión para gestionar tu plan.',onlyUnlimited:'La única suscripción disponible es ImportVerifier Unlimited.',legalNotReady:'La contratación está temporalmente desactivada hasta completar la información legal obligatoria del prestador. No se ha iniciado ningún cobro.',invalidRequest:'Solicitud no válida.',subscriptionRead:'No se puede consultar tu suscripción.',paymentPrepare:'No se ha podido preparar el pago.',siteUrl:'La URL pública de ImportVerifier no está configurada de forma segura.',stripePrice:'La configuración de Stripe no corresponde a Unlimited 9,95 €/mes. No se ha iniciado ningún cobro.',stripePage:'Stripe no ha devuelto una página de pago.',paymentOpen:'No se ha podido abrir el pago.',noSubscription:'Esta cuenta todavía no tiene una suscripción.',portalOpen:'No se ha podido abrir la gestión del plan.'
};
export const billingCopy: Record<Language,Copy> = {
  es,
  en:{...es,origin:'Request origin is not allowed.',signInCheckout:'Sign in to subscribe to Unlimited.',signInPortal:'Sign in to manage your plan.',onlyUnlimited:'The only available subscription is ImportVerifier Unlimited.',legalNotReady:'Subscriptions are temporarily disabled until the provider’s required legal information is complete. No charge has been started.',invalidRequest:'Invalid request.',subscriptionRead:'Your subscription could not be retrieved.',paymentPrepare:'The payment could not be prepared.',siteUrl:'ImportVerifier’s public URL is not configured securely.',stripePrice:'Stripe is not configured for Unlimited at €9.95/month. No charge has been started.',stripePage:'Stripe did not return a payment page.',paymentOpen:'The payment page could not be opened.',noSubscription:'This account does not have a subscription yet.',portalOpen:'Plan management could not be opened.'},
  fr:{...es,origin:'Origine de la requête non autorisée.',signInCheckout:'Connectez-vous pour souscrire à Unlimited.',signInPortal:'Connectez-vous pour gérer votre offre.',onlyUnlimited:'Le seul abonnement disponible est ImportVerifier Unlimited.',legalNotReady:'Les abonnements sont temporairement désactivés jusqu’à ce que les informations légales obligatoires du prestataire soient complètes. Aucun paiement n’a été initié.',invalidRequest:'Requête non valide.',subscriptionRead:'Impossible de consulter votre abonnement.',paymentPrepare:'Impossible de préparer le paiement.',siteUrl:'L’URL publique d’ImportVerifier n’est pas configurée de manière sécurisée.',stripePrice:'Stripe n’est pas configuré pour Unlimited à 9,95 €/mois. Aucun paiement n’a été initié.',stripePage:'Stripe n’a pas renvoyé de page de paiement.',paymentOpen:'Impossible d’ouvrir la page de paiement.',noSubscription:'Ce compte n’a pas encore d’abonnement.',portalOpen:'Impossible d’ouvrir la gestion de l’offre.'},
  de:{...es,origin:'Anfrageursprung ist nicht zulässig.',signInCheckout:'Melde dich an, um Unlimited zu abonnieren.',signInPortal:'Melde dich an, um deinen Tarif zu verwalten.',onlyUnlimited:'Das einzige verfügbare Abonnement ist ImportVerifier Unlimited.',legalNotReady:'Abonnements sind vorübergehend deaktiviert, bis die erforderlichen rechtlichen Anbieterangaben vollständig sind. Es wurde keine Zahlung gestartet.',invalidRequest:'Ungültige Anfrage.',subscriptionRead:'Dein Abonnement konnte nicht abgerufen werden.',paymentPrepare:'Die Zahlung konnte nicht vorbereitet werden.',siteUrl:'Die öffentliche ImportVerifier-URL ist nicht sicher konfiguriert.',stripePrice:'Stripe ist nicht für Unlimited zu 9,95 €/Monat konfiguriert. Es wurde keine Zahlung gestartet.',stripePage:'Stripe hat keine Zahlungsseite zurückgegeben.',paymentOpen:'Die Zahlungsseite konnte nicht geöffnet werden.',noSubscription:'Dieses Konto hat noch kein Abonnement.',portalOpen:'Die Tarifverwaltung konnte nicht geöffnet werden.'},
  it:{...es,origin:'Origine della richiesta non consentita.',signInCheckout:'Accedi per abbonarti a Unlimited.',signInPortal:'Accedi per gestire il tuo piano.',onlyUnlimited:'L’unico abbonamento disponibile è ImportVerifier Unlimited.',legalNotReady:'Gli abbonamenti sono temporaneamente disattivati finché le informazioni legali obbligatorie del fornitore non saranno complete. Non è stato avviato alcun addebito.',invalidRequest:'Richiesta non valida.',subscriptionRead:'Impossibile recuperare il tuo abbonamento.',paymentPrepare:'Impossibile preparare il pagamento.',siteUrl:'L’URL pubblico di ImportVerifier non è configurato in modo sicuro.',stripePrice:'Stripe non è configurato per Unlimited a 9,95 €/mese. Non è stato avviato alcun addebito.',stripePage:'Stripe non ha restituito una pagina di pagamento.',paymentOpen:'Impossibile aprire la pagina di pagamento.',noSubscription:'Questo account non ha ancora un abbonamento.',portalOpen:'Impossibile aprire la gestione del piano.'},
  pt:{...es,origin:'Origem do pedido não permitida.',signInCheckout:'Inicie sessão para subscrever o Unlimited.',signInPortal:'Inicie sessão para gerir o seu plano.',onlyUnlimited:'A única subscrição disponível é ImportVerifier Unlimited.',legalNotReady:'As subscrições estão temporariamente desativadas até que a informação legal obrigatória do prestador esteja completa. Não foi iniciado qualquer débito.',invalidRequest:'Pedido inválido.',subscriptionRead:'Não foi possível consultar a sua subscrição.',paymentPrepare:'Não foi possível preparar o pagamento.',siteUrl:'O URL público do ImportVerifier não está configurado de forma segura.',stripePrice:'O Stripe não está configurado para Unlimited a 9,95 €/mês. Não foi iniciado qualquer débito.',stripePage:'O Stripe não devolveu uma página de pagamento.',paymentOpen:'Não foi possível abrir a página de pagamento.',noSubscription:'Esta conta ainda não tem uma subscrição.',portalOpen:'Não foi possível abrir a gestão do plano.'}
};

export function billingText(language: Language, key: BillingMessageKey) { return billingCopy[language][key]; }
