import type { Language } from './landing-i18n';

export type DashboardCopyKey =
  | 'tabDashboard'|'tabDashboardDesc'|'tabProducts'|'tabProductsDesc'|'tabHistory'|'tabHistoryDesc'|'tabReports'|'tabReportsDesc'|'tabSettings'|'tabSettingsDesc'
  | 'privateSession'|'signOut'|'workspace'|'yourAccount'|'sections'|'plan'|'free'|'unlimited'|'freeUsage'|'remaining'|'used'|'calculating'|'viewUnlimited'
  | 'hello'|'welcome'|'dashboardSubtitle'|'newAnalysis'|'freeUsed'|'marketCoverage'|'available'|'upcoming'|'preparing'
  | 'euActiveTitle'|'euActiveBody'|'euDisclaimer'|'importAria'|'quotaTitle'|'analyzeFor'|'active'|'importBody'|'photo'|'text'|'max5mb'|'analyzing'|'upgrade'|'chooseFile'|'downloadTemplate'|'unlimitedUsage'|'freeAvailable'|'calculatingTrial'|'viewReports'|'uploading'|'importUrl'|'urlImportPlaceholder'|'urlImportButton'|'urlImportInvalid'|'urlImportFetchFailed'|'urlImportHelp'|'importFile'|'edit'|'uploadMore'|'checkChecklist'|'accountPrivacy'|'reportReady'|'reportType'|'marketAccess'|'downloadReport'|'exporting'|'openFromHistory'|'selectedAnalysis'|'saved'|'results'|'history'|'madeWith'|'noData'|'reviewNeeds'|'exportXlsx'|'exportPdf'
  | 'onboarding'|'firstReview'|'market'|'europeSelected'|'template'|'downloaded'|'readyDownload'|'analysis'|'catalogueSaved'|'uploadCatalogue'|'report'|'exported'|'overview'|'selectedAnalysis'|'panelReady'|'smallCatalogueTitle'|'smallCatalogueBody'|'firstCatalogue'|'preferTemplate'|'selected'|'viewResults'|'results'|'saved'|'rules'|'resultsCaption'|'product'|'indicator'|'priority'|'fieldsReview'|'keepReview'|'allProducts'|'close'|'archive'|'analysisHistory'|'page'|'loadingHistory'|'historyEmptyTitle'|'historyEmptyBody'|'createFirst'|'open'|'previous'|'next'
  | 'export'|'reportsReady'|'workingWith'|'detailedExcel'|'excelBody'|'downloadXlsx'|'executivePdf'|'pdfBody'|'downloadPdf'|'documentaryGuide'|'whatToRequest'|'whereGet'|'whatCheck'|'howGet'|'accountHeading'|'profile'|'changePassword'|'currentPlan'|'productWord'|'unlimitedTechnical'|'manageSubscription'|'ofFiveFree'|'freePlanBody'|'onlySubscription'|'unlimitedBody'|'unlimitedActive'|'billingOptions'|'monthly'|'annual'|'lifetime'|'custom'|'lifetimeActive'|'billingChoice'|'paymentError'|'portalError'|'templateDownloaded'|'checkoutSuccess'|'checkoutCancelled'|'analysisSaved'|'reportPdfReady'|'reportExcelReady'|'reportError'|'historyError'|'unsupportedMarket'|'fileTooLarge'|'fileNameTooLong'|'importError'|'openError'|'fileReadError'|'unsupportedVersion'
  | 'addUrl'|'urlPlaceholder'|'connectByUrl'|'pasteUrl';

type DashboardDictionary = Record<DashboardCopyKey,string>;

const es: DashboardDictionary = {
  tabDashboard:'Resumen',tabDashboardDesc:'Vista general',tabProducts:'Productos',tabProductsDesc:'Resultados del análisis',tabHistory:'Historial',tabHistoryDesc:'Análisis guardados',tabReports:'Informes',tabReportsDesc:'Exportaciones y documentación',tabSettings:'Ajustes',tabSettingsDesc:'Cuenta y plan',
  privateSession:'Sesión privada',signOut:'Cerrar sesión',workspace:'ESPACIO DE TRABAJO',yourAccount:'Tu cuenta',sections:'Secciones del panel',plan:'Plan',free:'Gratis',unlimited:'Ilimitado',freeUsage:'Uso gratuito',remaining:'{n} restantes',used:'{used} de {limit} usados',calculating:'Calculando…',viewUnlimited:'Ver Unlimited',
  hello:'Hola, {name}',welcome:'bienvenido',dashboardSubtitle:'Revisa el estado de tu catálogo, tus productos y tus exportaciones.',newAnalysis:'Nuevo análisis',freeUsed:'Has usado tus 5 productos gratuitos',marketCoverage:'Cobertura de mercado',available:'Disponible',upcoming:'Próximamente',preparing:'Preparando…',
  euActiveTitle:'Europa activa:',euActiveBody:'el verificador detecta campos básicos incompletos y genera una guía basada en fuentes oficiales.',euDisclaimer:'No certifica conformidad ni sustituye una evaluación jurídica o técnica.',importAria:'Importar productos desde foto, documento, texto, CSV o Excel',quotaTitle:'Has utilizado tus 5 productos gratuitos',analyzeFor:'Analiza para {market}',active:'ACTIVO',importBody:'Arrastra una foto, PDF, Word, texto, CSV o Excel de hasta 5 MB. Identificaremos los productos y conservaremos el análisis en tu historial privado.',photo:'FOTO',text:'TEXTO',max5mb:'Máx. 5 MB',analyzing:'Analizando…',upgrade:'Pasar a Unlimited',chooseFile:'Elegir archivo',downloadTemplate:'Descargar plantilla',unlimitedUsage:'Unlimited · análisis sin cuota comercial de productos',freeAvailable:'{remaining} de {limit} productos gratuitos disponibles',calculatingTrial:'Calculando tu cuota…',viewReports:'Ver informes',uploading:'Subiendo…',importUrl:'Pegar URL',urlImportPlaceholder:'https://ejemplo.com/catalogo.csv',urlImportButton:'Importar desde URL',urlImportInvalid:'La URL debe empezar por http:// o https://.',urlImportFetchFailed:'No se pudo cargar la URL. Comprueba que esté accesible y sea un archivo soportado.',urlImportHelp:'Pega una URL directa a un CSV, Excel, PDF o imagen compatible.',importFile:'Importar archivo',edit:'Editar',uploadMore:'Subir más',checkChecklist:'Revisar checklist',accountPrivacy:'Privacidad',reportReady:'Listo para exportar',reportType:'Tipo de informe',marketAccess:'Cobertura de mercado',downloadReport:'Descargar informe',exporting:'Exportando…',openFromHistory:'Abrir desde historial',selectedAnalysis:'Análisis seleccionado',saved:'Guardado',results:'Resultados',history:'Historial',madeWith:'Hecho con',noData:'Sin datos',reviewNeeds:'Revisión requerida',exportXlsx:'Exportar Excel',exportPdf:'Exportar PDF',
  onboarding:'PUESTA EN MARCHA',firstReview:'Tu primera revisión, sin dudas.',market:'Mercado',europeSelected:'Europa seleccionada',template:'Plantilla',downloaded:'Descargada',readyDownload:'Listo para descargar',analysis:'Análisis',catalogueSaved:'Catálogo guardado',uploadCatalogue:'Subir catálogo',report:'Informe',exported:'Exportado',overview:'Resumen',panelReady:'Panel listo',smallCatalogueTitle:'Empieza por un catálogo pequeño',smallCatalogueBody:'Con unos pocos productos verás qué información básica falta, qué pedir al proveedor y dónde comprobar las fuentes.',firstCatalogue:'Tu primer catálogo',preferTemplate:'Te recomendamos empezar con la plantilla',selected:'Seleccionado',viewResults:'Ver resultados',saved:'Guardado',rules:'reglas',resultsCaption:'Resultados del análisis',product:'Producto',indicator:'Indicador',priority:'Prioridad',fieldsReview:'Campos a revisar',keepReview:'Revisa primero la información más sensible',allProducts:'Todos los productos',close:'Cerrar',
  archive:'ARCHIVO',analysisHistory:'Historial de análisis',page:'Página {n}',loadingHistory:'Cargando tus análisis…',historyEmptyTitle:'Aquí aparecerá todo lo que analices',historyEmptyBody:'Sube un catálogo para crear tu primer análisis y conservarlo en privado.',createFirst:'Crear mi primer análisis',open:'Abrir',previous:'Anterior',next:'Siguiente',
  export:'EXPORTACIÓN',reportsReady:'Informes listos para trabajar',workingWith:'Estás trabajando con {file}.',detailedExcel:'Excel detallado',excelBody:'Descarga una hoja de cálculo con resultados clasificados y revisiones por producto.',downloadXlsx:'Descargar XLSX',executivePdf:'PDF ejecutivo',pdfBody:'Genera un resumen claro para compartir con tu equipo o tu cliente.',downloadPdf:'Descargar PDF',documentaryGuide:'Guía documental',whatToRequest:'Qué pedir al proveedor',whereGet:'Dónde comprobarlo',whatCheck:'Qué revisar',howGet:'Cómo obtenerlo',accountHeading:'CUENTA',profile:'Tu perfil',changePassword:'Cambiar contraseña',currentPlan:'PLAN ACTUAL',productWord:'productos',unlimitedTechnical:'Uso ilimitado comercialmente. Solo se mantiene un límite operativo técnico de protección.',manageSubscription:'Gestionar suscripción',ofFiveFree:'de 5 gratuitos',freePlanBody:'Tu prueba gratuita incluye exactamente 5 productos en total por cuenta.',onlySubscription:'solo en el plan suscrito',unlimitedBody:'ImportVerifier Unlimited elimina la cuota comercial por producto para análisis grandes y continuados.',unlimitedActive:'Unlimited activo',billingOptions:'Opciones de pago',monthly:'Mensual',annual:'Anual',lifetime:'Lifetime',custom:'Personalizada',lifetimeActive:'Pago único',billingChoice:'Elegir',paymentError:'No se pudo abrir el pago.',portalError:'No se pudo abrir el portal de gestión.',templateDownloaded:'Plantilla de Europa descargada. Sustituye el ejemplo por tus productos y conserva los cuatro encabezados.',checkoutSuccess:'Pago recibido. Stripe está confirmando Unlimited; vuelve en unos segundos.',checkoutCancelled:'El proceso de pago se canceló. Puedes intentarlo otra vez cuando quieras.',analysisSaved:'Análisis guardado para {market}.',reportPdfReady:'PDF listo para descargar.',reportExcelReady:'XLSX listo para descargar.',reportError:'No se pudo exportar el informe.',historyError:'No se pudo cargar el historial.',unsupportedMarket:'Este mercado aún no está disponible.',fileTooLarge:'El archivo supera el límite de 5 MB.',fileNameTooLong:'El nombre del archivo es demasiado largo.',importError:'No se pudo importar el archivo.',openError:'No se pudo abrir el análisis.',fileReadError:'No se pudo leer el archivo.',unsupportedVersion:'Este análisis usa una versión del motor no compatible.',
  addUrl:'Añadir URL',urlPlaceholder:'Pega una URL',connectByUrl:'Conectar por URL',pasteUrl:'Pega una URL para importar',
};

const en: DashboardDictionary = {
  ...es,
  tabDashboard:'Overview',tabDashboardDesc:'General view',tabProducts:'Products',tabProductsDesc:'Analysis results',tabHistory:'History',tabHistoryDesc:'Saved analyses',tabReports:'Reports',tabReportsDesc:'Exports and documentation',tabSettings:'Settings',tabSettingsDesc:'Account and plan',
  privateSession:'Private session',signOut:'Sign out',workspace:'WORKSPACE',yourAccount:'Your account',sections:'Panel sections',plan:'Plan',free:'Free',unlimited:'Unlimited',freeUsage:'Free usage',remaining:'{n} left',used:'{used} of {limit} used',calculating:'Calculating…',viewUnlimited:'View Unlimited',
  hello:'Hello, {name}',welcome:'welcome',dashboardSubtitle:'Check the status of your catalogue, products and exports.',newAnalysis:'New analysis',freeUsed:'You used all 5 free products',marketCoverage:'Market coverage',available:'Available',upcoming:'Coming soon',preparing:'Preparing…',
  euActiveTitle:'Europe active:',euActiveBody:'the verifier spots missing basic fields and produces guidance based on official sources.',euDisclaimer:'It does not certify compliance or replace legal or technical review.',importAria:'Import products from photo, document, text, CSV or Excel',quotaTitle:'You used all 5 free products',analyzeFor:'Analyse for {market}',active:'ACTIVE',importBody:'Drop a photo, PDF, Word, text, CSV or Excel file up to 5 MB. We will identify the products and keep the analysis in your private history.',photo:'PHOTO',text:'TEXT',max5mb:'Max. 5 MB',analyzing:'Analysing…',upgrade:'Upgrade to Unlimited',chooseFile:'Choose file',downloadTemplate:'Download template',unlimitedUsage:'Unlimited · no commercial product quota',freeAvailable:'{remaining} of {limit} free products available',calculatingTrial:'Calculating your quota…',viewReports:'View reports',uploading:'Uploading…',importUrl:'Paste URL',urlImportPlaceholder:'https://example.com/catalog.csv',urlImportButton:'Import from URL',urlImportInvalid:'The URL must start with http:// or https://.',urlImportFetchFailed:'The URL could not be loaded. Check that it is reachable and points to a supported file.',urlImportHelp:'Paste a direct URL to a compatible CSV, Excel, PDF or image.',importFile:'Import file',edit:'Edit',uploadMore:'Upload more',checkChecklist:'Check checklist',accountPrivacy:'Privacy',reportReady:'Ready to export',reportType:'Report type',marketAccess:'Market coverage',downloadReport:'Download report',exporting:'Exporting…',openFromHistory:'Open from history',selectedAnalysis:'Selected analysis',saved:'Saved',results:'Results',history:'History',madeWith:'Made with',noData:'No data',reviewNeeds:'Review needed',exportXlsx:'Export Excel',exportPdf:'Export PDF',
  onboarding:'GETTING STARTED',firstReview:'Your first review, without doubts.',market:'Market',europeSelected:'Europe selected',template:'Template',downloaded:'Downloaded',readyDownload:'Ready to download',analysis:'Analysis',catalogueSaved:'Catalogue saved',uploadCatalogue:'Upload catalogue',report:'Report',exported:'Exported',overview:'Overview',panelReady:'Panel ready',smallCatalogueTitle:'Start with a small catalogue',smallCatalogueBody:'With a few products you will quickly see which information is missing, what to ask the supplier for and where to check the sources.',firstCatalogue:'Your first catalogue',preferTemplate:'We recommend starting with the template',selected:'Selected',viewResults:'View results',saved:'Saved',rules:'rules',resultsCaption:'Analysis results',product:'Product',indicator:'Indicator',priority:'Priority',fieldsReview:'Fields to review',keepReview:'Review the most sensitive information first',allProducts:'All products',close:'Close',
  archive:'ARCHIVE',analysisHistory:'Analysis history',page:'Page {n}',loadingHistory:'Loading your analyses…',historyEmptyTitle:'Everything you analyse will appear here',historyEmptyBody:'Upload a catalogue to create your first private analysis.',createFirst:'Create my first analysis',open:'Open',previous:'Previous',next:'Next',
  export:'EXPORT',reportsReady:'Reports ready to work with',workingWith:'You are working with {file}.',detailedExcel:'Detailed Excel',excelBody:'Download a spreadsheet with classified results and product-level reviews.',downloadXlsx:'Download XLSX',executivePdf:'Executive PDF',pdfBody:'Generate a concise summary to share with your team or client.',downloadPdf:'Download PDF',documentaryGuide:'Documentary guide',whatToRequest:'What to ask the supplier',whereGet:'Where to verify it',whatCheck:'What to review',howGet:'How to obtain it',accountHeading:'ACCOUNT',profile:'Your profile',changePassword:'Change password',currentPlan:'CURRENT PLAN',productWord:'products',unlimitedTechnical:'Commercially unlimited usage. Only an operational technical safeguard remains.',manageSubscription:'Manage subscription',ofFiveFree:'of 5 free',freePlanBody:'Your free trial includes exactly 5 products total per account.',onlySubscription:'only in the subscribed plan',unlimitedBody:'ImportVerifier Unlimited removes the commercial product quota for large and continuous analysis.',unlimitedActive:'Unlimited active',billingOptions:'Payment options',monthly:'Monthly',annual:'Annual',lifetime:'Lifetime',custom:'Custom',lifetimeActive:'One-time payment',billingChoice:'Choose',paymentError:'The payment could not be opened.',portalError:'The management portal could not be opened.',templateDownloaded:'Europe template downloaded. Replace the example with your products and keep the four headers.',checkoutSuccess:'Payment received. Stripe is confirming Unlimited; please come back in a few seconds.',checkoutCancelled:'The payment was cancelled. You can try again anytime.',analysisSaved:'Analysis saved for {market}.',reportPdfReady:'PDF ready to download.',reportExcelReady:'XLSX ready to download.',reportError:'The report could not be exported.',historyError:'The history could not be loaded.',unsupportedMarket:'This market is not available yet.',fileTooLarge:'The file exceeds the 5 MB limit.',fileNameTooLong:'The filename is too long.',importError:'The file could not be imported.',openError:'The analysis could not be opened.',fileReadError:'The file could not be read.',unsupportedVersion:'This analysis uses an incompatible engine version.',
  addUrl:'Add URL',urlPlaceholder:'Paste a URL',connectByUrl:'Connect by URL',pasteUrl:'Paste a URL to import',
};

const fr: DashboardDictionary = { ...en,
  tabDashboard:'Aperçu',tabDashboardDesc:'Vue générale',tabProducts:'Produits',tabProductsDesc:'Résultats de l’analyse',tabHistory:'Historique',tabHistoryDesc:'Analyses enregistrées',tabReports:'Rapports',tabReportsDesc:'Exportations et documentation',tabSettings:'Réglages',tabSettingsDesc:'Compte et forfait',
  privateSession:'Session privée',signOut:'Se déconnecter',workspace:'ESPACE DE TRAVAIL',yourAccount:'Votre compte',sections:'Sections du panneau',plan:'Forfait',free:'Gratuit',unlimited:'Illimité',freeUsage:'Utilisation gratuite',remaining:'{n} restants',used:'{used} sur {limit} utilisés',calculating:'Calcul…',viewUnlimited:'Voir Unlimited',
  hello:'Bonjour, {name}',welcome:'bienvenue',dashboardSubtitle:'Contrôlez l’état de votre catalogue, produits et exports.',newAnalysis:'Nouvelle analyse',freeUsed:'Vous avez utilisé vos 5 produits gratuits',marketCoverage:'Couverture marché',available:'Disponible',upcoming:'Bientôt',preparing:'Préparation…',
  euActiveTitle:'Europe active :',euActiveBody:'le vérificateur détecte les champs de base manquants et produit un guide fondé sur des sources officielles.',euDisclaimer:'Il ne certifie pas la conformité ni ne remplace une évaluation juridique ou technique.',importAria:'Importer des produits depuis photo, document, texte, CSV ou Excel',quotaTitle:'Vous avez utilisé vos 5 produits gratuits',analyzeFor:'Analyser pour {market}',active:'ACTIF',importBody:'Déposez une photo, un PDF, Word, un texte, un CSV ou un Excel de 5 Mo maximum. Nous identifierons les produits et conserverons l’analyse dans votre historique privé.',photo:'PHOTO',text:'TEXTE',max5mb:'Max. 5 Mo',analyzing:'Analyse…',upgrade:'Passer à Unlimited',chooseFile:'Choisir un fichier',downloadTemplate:'Télécharger le modèle',unlimitedUsage:'Unlimited · analyses sans quota commercial',freeAvailable:'{remaining} sur {limit} produits gratuits disponibles',calculatingTrial:'Calcul du quota…',viewReports:'Voir les rapports',uploading:'Téléchargement…',importUrl:'Coller l’URL',urlImportPlaceholder:'https://exemple.com/catalogue.csv',urlImportButton:'Importer depuis l’URL',urlImportInvalid:'L’URL doit commencer par http:// ou https://.',urlImportFetchFailed:'L’URL n’a pas pu être chargée. Vérifiez qu’elle est accessible et qu’elle pointe vers un fichier pris en charge.',urlImportHelp:'Collez une URL directe vers un CSV, Excel, PDF ou image compatible.',importFile:'Importer un fichier',edit:'Modifier',uploadMore:'Téléverser plus',checkChecklist:'Vérifier la checklist',accountPrivacy:'Confidentialité',reportReady:'Prêt à exporter',reportType:'Type de rapport',marketAccess:'Couverture du marché',downloadReport:'Télécharger le rapport',exporting:'Export…',openFromHistory:'Ouvrir depuis l’historique',selectedAnalysis:'Analyse sélectionnée',saved:'Enregistré',results:'Résultats',history:'Historique',madeWith:'Conçu avec',noData:'Aucune donnée',reviewNeeds:'Révision nécessaire',exportXlsx:'Exporter Excel',exportPdf:'Exporter PDF',
  onboarding:'MISE EN ROUTE',firstReview:'Votre première vérification, sans doute.',market:'Marché',europeSelected:'Europe sélectionnée',template:'Modèle',downloaded:'Téléchargé',readyDownload:'Prêt à télécharger',analysis:'Analyse',catalogueSaved:'Catalogue enregistré',uploadCatalogue:'Téléverser le catalogue',report:'Rapport',exported:'Exporté',overview:'Aperçu',panelReady:'Panneau prêt',smallCatalogueTitle:'Commencez par un petit catalogue',smallCatalogueBody:'Avec quelques produits, vous verrez rapidement quelles informations manquent, ce qu’il faut demander au fournisseur et où vérifier les sources.',firstCatalogue:'Votre premier catalogue',preferTemplate:'Nous recommandons de démarrer avec le modèle',selected:'Sélectionné',viewResults:'Voir les résultats',saved:'Enregistré',rules:'règles',resultsCaption:'Résultats de l’analyse',product:'Produit',indicator:'Indicateur',priority:'Priorité',fieldsReview:'Champs à revoir',keepReview:'Vérifiez d’abord les informations les plus sensibles',allProducts:'Tous les produits',close:'Fermer',
  archive:'ARCHIVE',analysisHistory:'Historique des analyses',page:'Page {n}',loadingHistory:'Chargement de vos analyses…',historyEmptyTitle:'Tout ce que vous analysez apparaîtra ici',historyEmptyBody:'Téléversez un catalogue pour créer votre première analyse privée.',createFirst:'Créer ma première analyse',open:'Ouvrir',previous:'Précédent',next:'Suivant',
  export:'EXPORT',reportsReady:'Rapports prêts à l’emploi',workingWith:'Vous travaillez avec {file}.',detailedExcel:'Excel détaillé',excelBody:'Téléchargez une feuille de calcul avec résultats classés et revues par produit.',downloadXlsx:'Télécharger XLSX',executivePdf:'PDF exécutif',pdfBody:'Générez un résumé clair à partager avec votre équipe ou client.',downloadPdf:'Télécharger le PDF',documentaryGuide:'Guide documentaire',whatToRequest:'Que demander au fournisseur',whereGet:'Où le vérifier',whatCheck:'Ce qu’il faut revoir',howGet:'Comment l’obtenir',accountHeading:'COMPTE',profile:'Votre profil',changePassword:'Changer le mot de passe',currentPlan:'PLAN ACTUEL',productWord:'produits',unlimitedTechnical:'Usage commercial illimité. Seul un garde-fou technique opérationnel reste en place.',manageSubscription:'Gérer l’abonnement',ofFiveFree:'sur 5 gratuits',freePlanBody:'Votre essai gratuit comprend exactement 5 produits au total par compte.',onlySubscription:'uniquement dans le plan souscrit',unlimitedBody:'ImportVerifier Unlimited supprime le quota commercial par produit pour les analyses longues et continues.',unlimitedActive:'Unlimited actif',billingOptions:'Options de paiement',monthly:'Mensuel',annual:'Annuel',lifetime:'Lifetime',custom:'Personnalisée',lifetimeActive:'Paiement unique',billingChoice:'Choisir',paymentError:'Le paiement n’a pas pu être ouvert.',portalError:'Le portail de gestion n’a pas pu être ouvert.',templateDownloaded:'Modèle Europe téléchargé. Remplacez l’exemple par vos produits et conservez les quatre en-têtes.',checkoutSuccess:'Paiement reçu. Stripe confirme Unlimited; veuillez revenir dans quelques secondes.',checkoutCancelled:'Le paiement a été annulé. Vous pouvez réessayer quand vous le souhaitez.',analysisSaved:'Analyse enregistrée pour {market}.',reportPdfReady:'PDF prêt à télécharger.',reportExcelReady:'XLSX prêt à télécharger.',reportError:'Le rapport n’a pas pu être exporté.',historyError:'L’historique n’a pas pu être chargé.',unsupportedMarket:'Ce marché n’est pas encore disponible.',fileTooLarge:'Le fichier dépasse la limite de 5 Mo.',fileNameTooLong:'Le nom du fichier est trop long.',importError:'Le fichier n’a pas pu être importé.',openError:'L’analyse n’a pas pu être ouverte.',fileReadError:'Le fichier n’a pas pu être lu.',unsupportedVersion:'Cette analyse utilise une version incompatible du moteur.',
  addUrl:'Ajouter une URL',urlPlaceholder:'Collez une URL',connectByUrl:'Se connecter par URL',pasteUrl:'Collez une URL pour importer',
};

const de: DashboardDictionary = { ...en,
  tabDashboard:'Übersicht',tabDashboardDesc:'Allgemeine Ansicht',tabProducts:'Produkte',tabProductsDesc:'Analyseergebnisse',tabHistory:'Verlauf',tabHistoryDesc:'Gespeicherte Analysen',tabReports:'Berichte',tabReportsDesc:'Exporte und Dokumentation',tabSettings:'Einstellungen',tabSettingsDesc:'Konto und Tarif',
  privateSession:'Private Sitzung',signOut:'Abmelden',workspace:'ARBEITSBEREICH',yourAccount:'Dein Konto',sections:'Bereichsübersicht',plan:'Tarif',free:'Kostenlos',unlimited:'Unlimited',freeUsage:'Kostenlose Nutzung',remaining:'{n} übrig',used:'{used} von {limit} verwendet',calculating:'Berechne…',viewUnlimited:'Unlimited ansehen',
  hello:'Hallo, {name}',welcome:'willkommen',dashboardSubtitle:'Prüfe den Status deines Katalogs, deiner Produkte und Exporte.',newAnalysis:'Neue Analyse',freeUsed:'Du hast deine 5 kostenlosen Produkte genutzt',marketCoverage:'Marktabdeckung',available:'Verfügbar',upcoming:'Bald',preparing:'Bereite vor…',
  euActiveTitle:'Europa aktiv:',euActiveBody:'der Prüfer erkennt fehlende Basisdaten und erzeugt Hinweise auf Basis offizieller Quellen.',euDisclaimer:'Es zertifiziert keine Konformität und ersetzt keine rechtliche oder technische Prüfung.',importAria:'Produkte aus Foto, Dokument, Text, CSV oder Excel importieren',quotaTitle:'Du hast deine 5 kostenlosen Produkte genutzt',analyzeFor:'Analysieren für {market}',active:'AKTIV',importBody:'Lege eine Foto-, PDF-, Word-, Text-, CSV- oder Excel-Datei bis 5 MB ab. Wir erkennen die Produkte und speichern die Analyse in deinem privaten Verlauf.',photo:'FOTO',text:'TEXT',max5mb:'Max. 5 MB',analyzing:'Analysiere…',upgrade:'Auf Unlimited upgraden',chooseFile:'Datei wählen',downloadTemplate:'Vorlage herunterladen',unlimitedUsage:'Unlimited · keine kommerzielle Produktquote',freeAvailable:'{remaining} von {limit} kostenlosen Produkten verfügbar',calculatingTrial:'Quota wird berechnet…',viewReports:'Berichte ansehen',uploading:'Hochladen…',importUrl:'URL einfügen',urlImportPlaceholder:'https://beispiel.de/katalog.csv',urlImportButton:'Von URL importieren',urlImportInvalid:'Die URL muss mit http:// oder https:// beginnen.',urlImportFetchFailed:'Die URL konnte nicht geladen werden. Prüfe, ob sie erreichbar ist und auf eine unterstützte Datei zeigt.',urlImportHelp:'Füge eine direkte URL zu einer kompatiblen CSV-, Excel-, PDF- oder Bilddatei ein.',importFile:'Datei importieren',edit:'Bearbeiten',uploadMore:'Mehr hochladen',checkChecklist:'Checkliste prüfen',accountPrivacy:'Datenschutz',reportReady:'Bereit zum Export',reportType:'Berichtstyp',marketAccess:'Marktabdeckung',downloadReport:'Bericht herunterladen',exporting:'Exportiere…',openFromHistory:'Aus Verlauf öffnen',selectedAnalysis:'Ausgewählte Analyse',saved:'Gespeichert',results:'Ergebnisse',history:'Verlauf',madeWith:'Erstellt mit',noData:'Keine Daten',reviewNeeds:'Überprüfung erforderlich',exportXlsx:'Excel exportieren',exportPdf:'PDF exportieren',
  onboarding:'EINSTIEG',firstReview:'Deine erste Prüfung ohne Zweifel.',market:'Markt',europeSelected:'Europa ausgewählt',template:'Vorlage',downloaded:'Heruntergeladen',readyDownload:'Bereit zum Herunterladen',analysis:'Analyse',catalogueSaved:'Katalog gespeichert',uploadCatalogue:'Katalog hochladen',report:'Bericht',exported:'Exportiert',overview:'Übersicht',panelReady:'Panel bereit',smallCatalogueTitle:'Beginne mit einem kleinen Katalog',smallCatalogueBody:'Mit wenigen Produkten siehst du schnell, welche Informationen fehlen, was du beim Lieferanten anfragen musst und wo du die Quellen prüfen solltest.',firstCatalogue:'Dein erster Katalog',preferTemplate:'Wir empfehlen, mit der Vorlage zu starten',selected:'Ausgewählt',viewResults:'Ergebnisse ansehen',saved:'Gespeichert',rules:'Regeln',resultsCaption:'Analyseergebnisse',product:'Produkt',indicator:'Indikator',priority:'Priorität',fieldsReview:'Zu prüfende Felder',keepReview:'Prüfe zuerst die sensiblen Informationen',allProducts:'Alle Produkte',close:'Schließen',
  archive:'ARCHIV',analysisHistory:'Analyseverlauf',page:'Seite {n}',loadingHistory:'Deine Analysen werden geladen…',historyEmptyTitle:'Alles, was du analysierst, erscheint hier',historyEmptyBody:'Lade einen Katalog hoch, um deine erste private Analyse zu erstellen.',createFirst:'Meine erste Analyse erstellen',open:'Öffnen',previous:'Zurück',next:'Weiter',
  export:'EXPORT',reportsReady:'Berichte zum Arbeiten bereit',workingWith:'Du arbeitest mit {file}.',detailedExcel:'Detaillierte Excel-Datei',excelBody:'Lade eine Tabelle mit klassifizierten Ergebnissen und Produktprüfungen herunter.',downloadXlsx:'XLSX herunterladen',executivePdf:'Executive PDF',pdfBody:'Erzeuge eine kompakte Zusammenfassung für Team oder Kunde.',downloadPdf:'PDF herunterladen',documentaryGuide:'Dokumentationsleitfaden',whatToRequest:'Was du beim Lieferanten anfragen solltest',whereGet:'Wo du es prüfen kannst',whatCheck:'Was zu prüfen ist',howGet:'Wie du es erhältst',accountHeading:'KONTO',profile:'Dein Profil',changePassword:'Passwort ändern',currentPlan:'AKTUELLER TARIF',productWord:'Produkte',unlimitedTechnical:'Kommerzielle Nutzung unbegrenzt. Nur eine technische Schutzgrenze bleibt aktiv.',manageSubscription:'Abo verwalten',ofFiveFree:'von 5 kostenlos',freePlanBody:'Deine kostenlose Testphase umfasst genau 5 Produkte pro Konto.',onlySubscription:'nur im gewählten Tarif',unlimitedBody:'ImportVerifier Unlimited entfernt die kommerzielle Produktquote für große und fortlaufende Analysen.',unlimitedActive:'Unlimited aktiv',billingOptions:'Zahlungsoptionen',monthly:'Monatlich',annual:'Jährlich',lifetime:'Lifetime',custom:'Individuell',lifetimeActive:'Einmalzahlung',billingChoice:'Auswählen',paymentError:'Die Zahlung konnte nicht geöffnet werden.',portalError:'Das Management-Portal konnte nicht geöffnet werden.',templateDownloaded:'Europa-Vorlage heruntergeladen. Ersetze das Beispiel durch deine Produkte und behalte die vier Überschriften.',checkoutSuccess:'Zahlung erhalten. Stripe bestätigt Unlimited; bitte in wenigen Sekunden erneut prüfen.',checkoutCancelled:'Die Zahlung wurde abgebrochen. Du kannst es jederzeit erneut versuchen.',analysisSaved:'Analyse gespeichert für {market}.',reportPdfReady:'PDF zum Herunterladen bereit.',reportExcelReady:'XLSX zum Herunterladen bereit.',reportError:'Der Bericht konnte nicht exportiert werden.',historyError:'Der Verlauf konnte nicht geladen werden.',unsupportedMarket:'Dieser Markt ist noch nicht verfügbar.',fileTooLarge:'Die Datei überschreitet das 5-MB-Limit.',fileNameTooLong:'Der Dateiname ist zu lang.',importError:'Die Datei konnte nicht importiert werden.',openError:'Die Analyse konnte nicht geöffnet werden.',fileReadError:'Die Datei konnte nicht gelesen werden.',unsupportedVersion:'Diese Analyse verwendet eine inkompatible Motor-Version.',
  addUrl:'URL hinzufügen',urlPlaceholder:'URL einfügen',connectByUrl:'Per URL verbinden',pasteUrl:'URL zum Importieren einfügen',
};

const it: DashboardDictionary = { ...en,
  tabDashboard:'Panoramica',tabDashboardDesc:'Vista generale',tabProducts:'Prodotti',tabProductsDesc:'Risultati dell’analisi',tabHistory:'Cronologia',tabHistoryDesc:'Analisi salvate',tabReports:'Report',tabReportsDesc:'Esportazioni e documentazione',tabSettings:'Impostazioni',tabSettingsDesc:'Account e piano',
  privateSession:'Sessione privata',signOut:'Esci',workspace:'AREA DI LAVORO',yourAccount:'Il tuo account',sections:'Sezioni del pannello',plan:'Piano',free:'Gratis',unlimited:'Unlimited',freeUsage:'Utilizzo gratuito',remaining:'{n} rimasti',used:'{used} di {limit} usati',calculating:'Calcolo…',viewUnlimited:'Vedi Unlimited',
  hello:'Ciao, {name}',welcome:'benvenuto',dashboardSubtitle:'Controlla lo stato del tuo catalogo, dei prodotti e delle esportazioni.',newAnalysis:'Nuova analisi',freeUsed:'Hai usato i tuoi 5 prodotti gratuiti',marketCoverage:'Copertura mercato',available:'Disponibile',upcoming:'Presto',preparing:'Preparazione…',
  euActiveTitle:'Europa attiva:',euActiveBody:'il verificatore rileva campi base mancanti e genera una guida basata su fonti ufficiali.',euDisclaimer:'Non certifica conformità né sostituisce una valutazione legale o tecnica.',importAria:'Importa prodotti da foto, documento, testo, CSV o Excel',quotaTitle:'Hai usato i tuoi 5 prodotti gratuiti',analyzeFor:'Analizza per {market}',active:'ATTIVO',importBody:'Trascina una foto, PDF, Word, testo, CSV o Excel fino a 5 MB. Identificheremo i prodotti e conserveremo l’analisi nella tua cronologia privata.',photo:'FOTO',text:'TESTO',max5mb:'Max. 5 MB',analyzing:'Analisi…',upgrade:'Passa a Unlimited',chooseFile:'Scegli file',downloadTemplate:'Scarica modello',unlimitedUsage:'Unlimited · analisi senza quota commerciale',freeAvailable:'{remaining} di {limit} prodotti gratuiti disponibili',calculatingTrial:'Calcolo della quota…',viewReports:'Vedi report',uploading:'Caricamento…',importUrl:'Incolla URL',urlImportPlaceholder:'https://esempio.com/catalogo.csv',urlImportButton:'Importa da URL',urlImportInvalid:'L’URL deve iniziare con http:// o https://.',urlImportFetchFailed:'L’URL non è stata caricata. Controlla che sia raggiungibile e punti a un file supportato.',urlImportHelp:'Incolla un URL diretto a un CSV, Excel, PDF o immagine compatibile.',importFile:'Importa file',edit:'Modifica',uploadMore:'Carica altro',checkChecklist:'Controlla checklist',accountPrivacy:'Privacy',reportReady:'Pronto per esportare',reportType:'Tipo di report',marketAccess:'Copertura mercato',downloadReport:'Scarica report',exporting:'Esportazione…',openFromHistory:'Apri dalla cronologia',selectedAnalysis:'Analisi selezionata',saved:'Salvato',results:'Risultati',history:'Cronologia',madeWith:'Creato con',noData:'Nessun dato',reviewNeeds:'Revisione necessaria',exportXlsx:'Esporta Excel',exportPdf:'Esporta PDF',
  onboarding:'PRIMO PASSO',firstReview:'La tua prima revisione, senza dubbi.',market:'Mercato',europeSelected:'Europa selezionata',template:'Modello',downloaded:'Scaricato',readyDownload:'Pronto da scaricare',analysis:'Analisi',catalogueSaved:'Catalogo salvato',uploadCatalogue:'Carica catalogo',report:'Report',exported:'Esportato',overview:'Panoramica',panelReady:'Pannello pronto',smallCatalogueTitle:'Inizia con un catalogo piccolo',smallCatalogueBody:'Con pochi prodotti vedrai rapidamente quali informazioni mancano, cosa chiedere al fornitore e dove verificare le fonti.',firstCatalogue:'Il tuo primo catalogo',preferTemplate:'Ti consigliamo di iniziare con il modello',selected:'Selezionato',viewResults:'Vedi risultati',saved:'Salvato',rules:'regole',resultsCaption:'Risultati dell’analisi',product:'Prodotto',indicator:'Indicatore',priority:'Priorità',fieldsReview:'Campi da rivedere',keepReview:'Controlla prima le informazioni più sensibili',allProducts:'Tutti i prodotti',close:'Chiudi',
  archive:'ARCHIVIO',analysisHistory:'Cronologia delle analisi',page:'Pagina {n}',loadingHistory:'Caricamento delle tue analisi…',historyEmptyTitle:'Qui apparirà tutto ciò che analizzi',historyEmptyBody:'Carica un catalogo per creare la tua prima analisi privata.',createFirst:'Crea la mia prima analisi',open:'Apri',previous:'Precedente',next:'Successivo',
  export:'EXPORT',reportsReady:'Report pronti da usare',workingWith:'Stai lavorando con {file}.',detailedExcel:'Excel dettagliato',excelBody:'Scarica un foglio di calcolo con risultati classificati e revisioni per prodotto.',downloadXlsx:'Scarica XLSX',executivePdf:'PDF esecutivo',pdfBody:'Genera un riepilogo chiaro da condividere con il tuo team o cliente.',downloadPdf:'Scarica PDF',documentaryGuide:'Guida documentale',whatToRequest:'Cosa chiedere al fornitore',whereGet:'Dove verificarlo',whatCheck:'Cosa controllare',howGet:'Come ottenerlo',accountHeading:'ACCOUNT',profile:'Il tuo profilo',changePassword:'Cambia password',currentPlan:'PIANO ATTUALE',productWord:'prodotti',unlimitedTechnical:'Utilizzo commerciale illimitato. Rimane solo un limite tecnico operativo.',manageSubscription:'Gestisci abbonamento',ofFiveFree:'di 5 gratuiti',freePlanBody:'La tua prova gratuita include esattamente 5 prodotti totali per account.',onlySubscription:'solo nel piano sottoscritto',unlimitedBody:'ImportVerifier Unlimited elimina la quota commerciale per prodotto per analisi grandi e continue.',unlimitedActive:'Unlimited attivo',billingOptions:'Opzioni di pagamento',monthly:'Mensile',annual:'Annuale',lifetime:'Lifetime',custom:'Personalizzata',lifetimeActive:'Pagamento unico',billingChoice:'Scegli',paymentError:'Il pagamento non si è potuto aprire.',portalError:'Il portale di gestione non si è potuto aprire.',templateDownloaded:'Modello Europa scaricato. Sostituisci l’esempio con i tuoi prodotti e conserva le quattro intestazioni.',checkoutSuccess:'Pagamento ricevuto. Stripe sta confermando Unlimited; torna tra qualche secondo.',checkoutCancelled:'Il pagamento è stato annullato. Puoi riprovare quando vuoi.',analysisSaved:'Analisi salvata per {market}.',reportPdfReady:'PDF pronto da scaricare.',reportExcelReady:'XLSX pronto da scaricare.',reportError:'Il report non è stato esportato.',historyError:'La cronologia non è stata caricata.',unsupportedMarket:'Questo mercato non è ancora disponibile.',fileTooLarge:'Il file supera il limite di 5 MB.',fileNameTooLong:'Il nome del file è troppo lungo.',importError:'Il file non è stato importato.',openError:'L’analisi non è stata aperta.',fileReadError:'Il file non è stato letto.',unsupportedVersion:'Questa analisi usa una versione incompatibile del motore.',
  addUrl:'Aggiungi URL',urlPlaceholder:'Incolla un URL',connectByUrl:'Connetti via URL',pasteUrl:'Incolla un URL da importare',
};

const pt: DashboardDictionary = { ...en,
  tabDashboard:'Visão geral',tabDashboardDesc:'Vista geral',tabProducts:'Produtos',tabProductsDesc:'Resultados da análise',tabHistory:'Histórico',tabHistoryDesc:'Análises guardadas',tabReports:'Relatórios',tabReportsDesc:'Exportações e documentação',tabSettings:'Definições',tabSettingsDesc:'Conta e plano',
  privateSession:'Sessão privada',signOut:'Terminar sessão',workspace:'ESPAÇO DE TRABALHO',yourAccount:'A tua conta',sections:'Secções do painel',plan:'Plano',free:'Grátis',unlimited:'Unlimited',freeUsage:'Uso gratuito',remaining:'{n} restantes',used:'{used} de {limit} usados',calculating:'A calcular…',viewUnlimited:'Ver Unlimited',
  hello:'Olá, {name}',welcome:'bem-vindo',dashboardSubtitle:'Consulta o estado do teu catálogo, produtos e exportações.',newAnalysis:'Nova análise',freeUsed:'Usaste os teus 5 produtos gratuitos',marketCoverage:'Cobertura do mercado',available:'Disponível',upcoming:'Em breve',preparing:'A preparar…',
  euActiveTitle:'Europa ativa:',euActiveBody:'o verificador detecta campos básicos em falta e gera uma orientação com base em fontes oficiais.',euDisclaimer:'Não certifica conformidade nem substitui uma revisão jurídica ou técnica.',importAria:'Importar produtos a partir de foto, documento, texto, CSV ou Excel',quotaTitle:'Usaste os teus 5 produtos gratuitos',analyzeFor:'Analisar para {market}',active:'ATIVO',importBody:'Arrasta um ficheiro de foto, PDF, Word, texto, CSV ou Excel até 5 MB. Iremos identificar os produtos e guardar a análise no teu histórico privado.',photo:'FOTO',text:'TEXTO',max5mb:'Máx. 5 MB',analyzing:'A analisar…',upgrade:'Passar para Unlimited',chooseFile:'Escolher ficheiro',downloadTemplate:'Descarregar modelo',unlimitedUsage:'Unlimited · análises sem quota comercial',freeAvailable:'{remaining} de {limit} produtos gratuitos disponíveis',calculatingTrial:'A calcular o teu quota…',viewReports:'Ver relatórios',uploading:'A carregar…',importUrl:'Colar URL',urlImportPlaceholder:'https://exemplo.com/catalogo.csv',urlImportButton:'Importar por URL',urlImportInvalid:'A URL deve começar em http:// ou https://.',urlImportFetchFailed:'A URL não pôde ser carregada. Verifica se está acessível e aponta para um ficheiro suportado.',urlImportHelp:'Cola uma URL direta para um CSV, Excel, PDF ou imagem compatível.',importFile:'Importar ficheiro',edit:'Editar',uploadMore:'Carregar mais',checkChecklist:'Verificar checklist',accountPrivacy:'Privacidade',reportReady:'Pronto para exportar',reportType:'Tipo de relatório',marketAccess:'Cobertura do mercado',downloadReport:'Descarregar relatório',exporting:'A exportar…',openFromHistory:'Abrir do histórico',selectedAnalysis:'Análise selecionada',saved:'Guardado',results:'Resultados',history:'Histórico',madeWith:'Feito com',noData:'Sem dados',reviewNeeds:'Revisão necessária',exportXlsx:'Exportar Excel',exportPdf:'Exportar PDF',
  onboarding:'INÍCIO',firstReview:'A tua primeira revisão, sem dúvidas.',market:'Mercado',europeSelected:'Europa selecionada',template:'Modelo',downloaded:'Descarregado',readyDownload:'Pronto a descarregar',analysis:'Análise',catalogueSaved:'Catálogo guardado',uploadCatalogue:'Carregar catálogo',report:'Relatório',exported:'Exportado',overview:'Resumo',panelReady:'Painel pronto',smallCatalogueTitle:'Começa por um catálogo pequeno',smallCatalogueBody:'Com poucos produtos, verás rapidamente que informações faltam, o que pedir ao fornecedor e onde confirmar as fontes.',firstCatalogue:'O teu primeiro catálogo',preferTemplate:'Recomendamos começar pelo modelo',selected:'Selecionado',viewResults:'Ver resultados',saved:'Guardado',rules:'regras',resultsCaption:'Resultados da análise',product:'Produto',indicator:'Indicador',priority:'Prioridade',fieldsReview:'Campos a rever',keepReview:'Revisa primeiro as informações mais sensíveis',allProducts:'Todos os produtos',close:'Fechar',
  archive:'ARQUIVO',analysisHistory:'Histórico de análises',page:'Página {n}',loadingHistory:'A carregar as tuas análises…',historyEmptyTitle:'Tudo o que analisares aparecerá aqui',historyEmptyBody:'Carrega um catálogo para criar a tua primeira análise privada.',createFirst:'Criar a minha primeira análise',open:'Abrir',previous:'Anterior',next:'Seguinte',
  export:'EXPORTAÇÃO',reportsReady:'Relatórios prontos para trabalhar',workingWith:'Estás a trabalhar com {file}.',detailedExcel:'Excel detalhado',excelBody:'Descarrega uma folha de cálculo com resultados classificados e revisões por produto.',downloadXlsx:'Descarregar XLSX',executivePdf:'PDF executivo',pdfBody:'Gera um resumo claro para partilhar com a tua equipa ou cliente.',downloadPdf:'Descarregar PDF',documentaryGuide:'Guia documental',whatToRequest:'O que pedir ao fornecedor',whereGet:'Onde verificar',whatCheck:'O que rever',howGet:'Como obter',accountHeading:'CONTA',profile:'O teu perfil',changePassword:'Alterar palavra-passe',currentPlan:'PLANO ATUAL',productWord:'produtos',unlimitedTechnical:'Uso comercial ilimitado. Mantém-se apenas um limite técnico operativo.',manageSubscription:'Gerir subscrição',ofFiveFree:'de 5 gratuitos',freePlanBody:'A tua avaliação gratuita inclui exatamente 5 produtos no total por conta.',onlySubscription:'só no plano subscrito',unlimitedBody:'ImportVerifier Unlimited remove a quota comercial por produto em análises grandes e contínuas.',unlimitedActive:'Unlimited ativo',billingOptions:'Opções de pagamento',monthly:'Mensal',annual:'Anual',lifetime:'Lifetime',custom:'Personalizada',lifetimeActive:'Pagamento único',billingChoice:'Escolher',paymentError:'Não foi possível abrir o pagamento.',portalError:'Não foi possível abrir o portal de gestão.',templateDownloaded:'Modelo Europa descarregado. Substitui o exemplo pelos teus produtos e mantém os quatro cabeçalhos.',checkoutSuccess:'Pagamento recebido. A Stripe está a confirmar Unlimited; volta em alguns segundos.',checkoutCancelled:'O pagamento foi cancelado. Podes tentar outra vez quando quiseres.',analysisSaved:'Análise guardada para {market}.',reportPdfReady:'PDF pronto a descarregar.',reportExcelReady:'XLSX pronto a descarregar.',reportError:'Não foi possível exportar o relatório.',historyError:'Não foi possível carregar o histórico.',unsupportedMarket:'Este mercado ainda não está disponível.',fileTooLarge:'O ficheiro excede o limite de 5 MB.',fileNameTooLong:'O nome do ficheiro é demasiado longo.',importError:'Não foi possível importar o ficheiro.',openError:'Não foi possível abrir a análise.',fileReadError:'Não foi possível ler o ficheiro.',unsupportedVersion:'Esta análise usa uma versão incompatível do motor.',
  addUrl:'Adicionar URL',urlPlaceholder:'Colar URL',connectByUrl:'Conectar por URL',pasteUrl:'Cola uma URL para importar',
};

export const dashboardDictionaries: Record<Language,DashboardDictionary> = { es,en,fr,de,it,pt };

export function dashboardText(language: Language, key: DashboardCopyKey, values: Record<string,string|number> = {}): string {
  let text = dashboardDictionaries[language][key];
  for (const [name,value] of Object.entries(values)) text = text.replaceAll(`{${name}}`, String(value));
  return text;
}
