import { Product } from './analysis';

export const GUIDE_VERSION = 'document-guide-v1 / 2026-08-28';
export const GUIDE_SCOPE = 'Guía orientativa: un campo vacío no demuestra que falte un documento. No se han recibido ni validado documentos. Los requisitos exactos dependen de la categoría, características, país de venta y papel del operador.';
export const SOURCES = {
  gpsr: 'https://eur-lex.europa.eu/eli/reg/2023/988/oj?locale=es',
  ce: 'https://single-market-economy.ec.europa.eu/single-market/goods/ce-marking/manufacturers_en',
  assessment: 'https://europa.eu/youreurope/business/product-rules-compliance/general-product-compliance/conformity-assessment/index_es.htm',
};
export type DocumentAction = { title: string; status: string; condition: string; obtain: string; check: string; source: string };
export function documentationFor(p: Product): DocumentAction[] {
  const state = (value: string) => value.trim() ? 'Dato aportado; sin verificar' : 'Dato no aportado';
  return [
    { title: 'Identificación del fabricante', status: state(p.manufacturer), condition: 'Para productos dentro del ámbito del GPSR: revisar artículos 9 y 19 y normativa específica.', obtain: 'Solicitar al fabricante o proveedor razón social, dirección postal y electrónica y fotografías de la etiqueta del modelo concreto.', check: 'Contrastar los datos con producto, embalaje y oferta online. Un nombre comercial aislado puede ser insuficiente.', source: SOURCES.gpsr },
    { title: 'Operador responsable en la UE', status: state(p.responsible), condition: 'Determinar qué operador establecido en la UE asume esta función; no implica contratar siempre un representante. GPSR, artículos 16 y 19.', obtain: 'Pedir al fabricante o importador la identidad, contactos y función del operador. Si actúa un representante autorizado, solicitar el mandato escrito pertinente.', check: 'Comprobar establecimiento en la UE, modelo cubierto y datos exigibles en etiqueta y oferta. No inventar contactos.', source: SOURCES.gpsr },
    { title: 'Instrucciones y advertencias', status: state(p.warning), condition: 'Según los riesgos y uso del producto; no toda ausencia implica incumplimiento. GPSR, artículos 9 y 19.', obtain: 'Solicitar al fabricante el manual y las advertencias de seguridad del modelo, en los idiomas exigidos en los mercados de venta.', check: 'Revisar correspondencia con el modelo, uso previsto, riesgos y legibilidad. No sustituir por advertencias genéricas.', source: SOURCES.gpsr },
    { title: 'Ficha de clasificación del producto', status: 'Información adicional necesaria', condition: 'Necesaria antes de determinar obligaciones documentales concretas.', obtain: 'Recopilar con el proveedor: modelo/SKU, categoría, materiales, uso, edad destinataria, alimentación eléctrica o radio, país de venta y tu papel (fabricante, importador o distribuidor).', check: 'No deducir requisitos únicamente del nombre del producto. Con estos datos, contrastar normativa aplicable.', source: SOURCES.assessment },
    { title: 'Documentación técnica y análisis de riesgos', status: 'Existencia no comprobada', condition: 'Para productos sujetos al GPSR, artículo 9; complementar con legislación sectorial aplicable.', obtain: 'Solicitar al fabricante confirmación de su expediente técnico y análisis de riesgos. El fabricante los elabora; puede necesitar apoyo técnico especializado.', check: 'Comprobar identificación del modelo, descripción, riesgos, medidas y evidencias. El acceso al expediente completo depende del papel del operador; no es una descarga pública.', source: SOURCES.gpsr },
    { title: 'Declaración UE de conformidad', status: 'Aplicabilidad pendiente', condition: 'Solo si la legislación aplicable exige esta declaración; no todos los productos requieren marcado CE.', obtain: 'Si procede, pedir al fabricante la declaración firmada del modelo concreto. Una plantilla vacía o un certificado genérico del proveedor no la sustituye.', check: 'Revisar modelo, fabricante, legislación citada, fecha y firma. No marcar como ausente hasta determinar aplicabilidad y solicitarla.', source: SOURCES.ce },
    { title: 'Ensayos y certificados específicos', status: 'Aplicabilidad pendiente', condition: 'Depende de la categoría y procedimiento de evaluación; no siempre exige un laboratorio externo u organismo notificado.', obtain: 'Pedir al fabricante evidencias de los ensayos aplicables. Si faltan, definir con un especialista qué ensayos y qué laboratorio u organismo resultan necesarios.', check: 'Contrastar modelo, alcance, métodos y resultados. No recomendar comprar un certificado universal de cumplimiento.', source: SOURCES.assessment },
  ];
}
