import type { Language } from './landing-i18n';

export type EvidenceApiKey = 'signIn' | 'invalidAnalysis' | 'read' | 'origin' | 'invalidData' | 'validateAnalysis' | 'missingProduct' | 'wrongRequirement' | 'save' | 'invalid';
type Copy = Record<EvidenceApiKey, string>;
const es: Copy = { signIn:'Inicia sesión.',invalidAnalysis:'Análisis no válido.',read:'No se puede leer la evidencia.',origin:'Origen no permitido.',invalidData:'Datos de evidencia no válidos.',validateAnalysis:'No se ha podido validar el análisis.',missingProduct:'El producto no existe en este análisis.',wrongRequirement:'La evidencia no corresponde a un requisito regulatorio de este producto.',save:'No se ha podido guardar la evidencia.',invalid:'Datos no válidos.' };
export const evidenceApiCopy: Record<Language, Copy> = {
  es,
  en:{...es,signIn:'Sign in.',invalidAnalysis:'Invalid analysis.',read:'The evidence cannot be read.',origin:'Request origin is not allowed.',invalidData:'Invalid evidence data.',validateAnalysis:'The analysis could not be validated.',missingProduct:'The product does not exist in this analysis.',wrongRequirement:'The evidence does not correspond to a regulatory requirement for this product.',save:'The evidence could not be saved.',invalid:'Invalid data.'},
  fr:{...es,signIn:'Connectez-vous.',invalidAnalysis:'Analyse non valide.',read:'Impossible de lire les preuves.',origin:'Origine de la requête non autorisée.',invalidData:'Données de preuve non valides.',validateAnalysis:'Impossible de valider l’analyse.',missingProduct:'Le produit n’existe pas dans cette analyse.',wrongRequirement:'La preuve ne correspond pas à une exigence réglementaire de ce produit.',save:'Impossible d’enregistrer la preuve.',invalid:'Données non valides.'},
  de:{...es,signIn:'Melden Sie sich an.',invalidAnalysis:'Ungültige Analyse.',read:'Die Nachweise können nicht gelesen werden.',origin:'Anfrageursprung ist nicht zulässig.',invalidData:'Ungültige Nachweisdaten.',validateAnalysis:'Die Analyse konnte nicht validiert werden.',missingProduct:'Das Produkt ist in dieser Analyse nicht vorhanden.',wrongRequirement:'Der Nachweis gehört zu keiner regulatorischen Anforderung dieses Produkts.',save:'Der Nachweis konnte nicht gespeichert werden.',invalid:'Ungültige Daten.'},
  it:{...es,signIn:'Accedi.',invalidAnalysis:'Analisi non valida.',read:'Impossibile leggere le evidenze.',origin:'Origine della richiesta non consentita.',invalidData:'Dati dell’evidenza non validi.',validateAnalysis:'Impossibile validare l’analisi.',missingProduct:'Il prodotto non esiste in questa analisi.',wrongRequirement:'L’evidenza non corrisponde a un requisito normativo di questo prodotto.',save:'Impossibile salvare l’evidenza.',invalid:'Dati non validi.'},
  pt:{...es,signIn:'Inicie sessão.',invalidAnalysis:'Análise inválida.',read:'Não é possível ler a evidência.',origin:'Origem do pedido não permitida.',invalidData:'Dados de evidência inválidos.',validateAnalysis:'Não foi possível validar a análise.',missingProduct:'O produto não existe nesta análise.',wrongRequirement:'A evidência não corresponde a um requisito regulamentar deste produto.',save:'Não foi possível guardar a evidência.',invalid:'Dados inválidos.'},
};
export function evidenceApiText(language: Language, key: EvidenceApiKey): string { return evidenceApiCopy[language][key]; }
