export const langs = ['es','en','fr','de','it','pt'] as const;
export type Lang = typeof langs[number];
export const copy: Record<Lang, Record<string,string>> = {
 es:{tag:'COMPLIANCE INTELLIGENCE PARA EUROPA',title:'Encuentra riesgos en tu catálogo antes que el marketplace.',lead:'Importa CSV o Excel, calcula un Risk Score explicable y prioriza qué productos requieren revisión.',scan:'Analizar catálogo',demo:'Ver demostración',login:'Entrar',plans:'Planes',dashboard:'Dashboard',products:'Productos',history:'Historial',reports:'Informes',settings:'Ajustes'},
 en:{tag:'COMPLIANCE INTELLIGENCE FOR EUROPE',title:'Find catalogue risks before the marketplace does.',lead:'Import CSV or Excel, calculate an explainable Risk Score and prioritize products that need review.',scan:'Scan catalogue',demo:'View demo',login:'Sign in',plans:'Plans',dashboard:'Dashboard',products:'Products',history:'History',reports:'Reports',settings:'Settings'},
 fr:{tag:'COMPLIANCE INTELLIGENCE POUR L’EUROPE',title:'Détectez les risques du catalogue avant la marketplace.',lead:'Importez CSV ou Excel, calculez un Risk Score explicable et priorisez les produits à vérifier.',scan:'Analyser le catalogue',demo:'Voir la démo',login:'Connexion',plans:'Offres',dashboard:'Tableau de bord',products:'Produits',history:'Historique',reports:'Rapports',settings:'Réglages'},
 de:{tag:'COMPLIANCE INTELLIGENCE FÜR EUROPA',title:'Erkenne Katalogrisiken vor dem Marktplatz.',lead:'CSV oder Excel importieren, erklärbaren Risk Score berechnen und Prüfungen priorisieren.',scan:'Katalog analysieren',demo:'Demo ansehen',login:'Anmelden',plans:'Tarife',dashboard:'Dashboard',products:'Produkte',history:'Verlauf',reports:'Berichte',settings:'Einstellungen'},
 it:{tag:'COMPLIANCE INTELLIGENCE PER L’EUROPA',title:'Trova i rischi del catalogo prima del marketplace.',lead:'Importa CSV o Excel, calcola un Risk Score spiegabile e dai priorità ai prodotti da verificare.',scan:'Analizza catalogo',demo:'Vedi demo',login:'Accedi',plans:'Piani',dashboard:'Dashboard',products:'Prodotti',history:'Cronologia',reports:'Report',settings:'Impostazioni'},
 pt:{tag:'COMPLIANCE INTELLIGENCE PARA A EUROPA',title:'Encontre riscos no catálogo antes do marketplace.',lead:'Importe CSV ou Excel, calcule um Risk Score explicável e priorize produtos para revisão.',scan:'Analisar catálogo',demo:'Ver demonstração',login:'Entrar',plans:'Planos',dashboard:'Painel',products:'Produtos',history:'Histórico',reports:'Relatórios',settings:'Definições'}
};
