import type { Language } from './landing-i18n';

type IntelligenceCopy = {
  aria: string;
  heroTitle: string;
  heroLead: string;
  loading: string;
  noAnalysis: string;
  loadError: string;
  aiLead: string;
  active: string;
  productLabel: string;
  defaultQuestion: string;
  questionPlaceholder: string;
  asking: string;
  ask: string;
  aiError: string;
  aiDisclaimer: string;
  twinLead: string;
  live: string;
  unclassified: string;
  category: string;
  confidence: string;
  evidenceAvailable: string;
  pendingReview: string;
  readinessDisclaimer: string;
  noClassification: string;
  radarLead: string;
  officialSources: string;
  radar: string;
  action: string;
  review: string;
  information: string;
  context: string;
  officialSource: string;
  radarNoMatch: string;
  radarNoEvents: string;
  radarEmpty: string;
  connectLead: string;
  connectors: string;
  upcomingAuthorize: string;
  platformPlaceholder: string;
  detect: string;
  platformDetected: string;
  authorizationPending: string;
  unknownPlatform: string;
};

const es: IntelligenceCopy = {
  aria: 'Suite de inteligencia ImportVerifier',
  heroTitle: 'Una capa inteligente sobre cada producto.',
  heroLead: 'Pregunta, entiende el estado regulatorio, prioriza cambios y prepara conexiones con tus canales de venta desde un único lugar.',
  loading: 'Preparando la inteligencia de tu último análisis…',
  noAnalysis: 'Crea tu primer análisis para activar ImportVerifier AI, Regulatory Twin e Impact Radar.',
  loadError: 'No se ha podido cargar la capa de inteligencia. El resto del panel sigue disponible.',
  aiLead: 'Asistente regulatorio contextual. Responde a partir de tu producto, reglas y evidencias guardadas en tu cuenta.',
  active: 'ACTIVO', productLabel: 'Producto para consultar',
  defaultQuestion: '¿Qué me falta para poder avanzar con este producto?',
  questionPlaceholder: 'Pregunta qué falta, qué pedir al proveedor o por qué aplica una norma…',
  asking: 'Analizando…', ask: 'Preguntar a ImportVerifier AI', aiError: 'No se ha podido consultar ImportVerifier AI.',
  aiDisclaimer: 'El contexto se reconstruye en el servidor desde tu análisis y evidencia guardada. Asistencia orientativa; ImportVerifier no emite certificaciones ni sustituye evaluación jurídica o técnica especializada.',
  twinLead: 'Gemelo regulatorio vivo del producto seleccionado.', live: 'VIVO', unclassified: 'SIN CLASIFICAR', category: 'Categoría', confidence: 'Confianza', evidenceAvailable: 'Evidencia disponible', pendingReview: 'Pendiente / revisar', readinessDisclaimer: 'El readiness refleja el estado de evidencia guardado por el usuario; no equivale a una certificación de conformidad.', noClassification: 'No hay una clasificación regulatoria disponible para este producto.',
  radarLead: 'Prioriza cambios oficiales que coinciden con las características del producto seleccionado.', officialSources: 'FUENTES OFICIALES', radar: 'RADAR', action: 'Acción', review: 'Revisar', information: 'Información', context: 'Contexto', officialSource: 'Fuente oficial', radarNoMatch: 'Hay cambios oficiales guardados, pero ninguno coincide todavía con las palabras clave del producto seleccionado.', radarNoEvents: 'Todavía no hay eventos regulatorios oficiales persistidos; estos puntos proceden del análisis actual del producto.', radarEmpty: 'Sin cambios oficiales relevantes ni impactos destacados para este producto.',
  connectLead: 'Base de integración preparada para importar catálogos y refrescar su estado desde las principales plataformas.', connectors: 'CONECTORES', upcomingAuthorize: 'Próximamente · Autorizar', platformPlaceholder: 'Pega una URL HTTPS de Shopify, Amazon o Etsy para detectar la plataforma', detect: 'Detectar', platformDetected: 'Plataforma detectada', authorizationPending: 'La autorización se activará cuando la integración oficial esté configurada.', unknownPlatform: 'No se ha reconocido una URL HTTPS compatible.'
};

export const intelligenceCopy: Record<Language, IntelligenceCopy> = {
  es,
  en: { ...es, aria:'ImportVerifier Intelligence Suite', heroTitle:'An intelligent layer for every product.', heroLead:'Ask questions, understand regulatory status, prioritise changes and prepare sales-channel connections from one place.', loading:'Preparing intelligence for your latest analysis…', noAnalysis:'Create your first analysis to activate ImportVerifier AI, Regulatory Twin and Impact Radar.', loadError:'The intelligence layer could not be loaded. The rest of the dashboard remains available.', aiLead:'Contextual regulatory assistant. It answers from your product, rules and evidence stored in your account.', active:'ACTIVE', productLabel:'Product to query', defaultQuestion:'What is missing before I can move forward with this product?', questionPlaceholder:'Ask what is missing, what to request from the supplier or why a rule may apply…', asking:'Analysing…', ask:'Ask ImportVerifier AI', aiError:'ImportVerifier AI could not be reached.', aiDisclaimer:'Context is rebuilt on the server from your analysis and stored evidence. Advisory assistance only; ImportVerifier does not issue certifications or replace specialist legal or technical assessment.', twinLead:'Live regulatory twin for the selected product.', live:'LIVE', unclassified:'UNCLASSIFIED', category:'Category', confidence:'Confidence', evidenceAvailable:'Evidence available', pendingReview:'Pending / review', readinessDisclaimer:'Readiness reflects the evidence state stored by the user; it is not a certification of conformity.', noClassification:'No regulatory classification is available for this product.', radarLead:'Prioritises official changes that match the selected product characteristics.', officialSources:'OFFICIAL SOURCES', radar:'RADAR', action:'Action', review:'Review', information:'Information', context:'Context', officialSource:'Official source', radarNoMatch:'Official changes are stored, but none currently match the selected product keywords.', radarNoEvents:'No official regulatory events are persisted yet; these points come from the current product analysis.', radarEmpty:'No relevant official changes or highlighted impacts for this product.', connectLead:'Integration foundation prepared to import catalogues and refresh their status from major platforms.', connectors:'CONNECTORS', upcomingAuthorize:'Coming soon · Authorise', platformPlaceholder:'Paste an HTTPS Shopify, Amazon or Etsy URL to detect the platform', detect:'Detect', platformDetected:'Platform detected', authorizationPending:'Authorisation will be enabled when the official integration is configured.', unknownPlatform:'No compatible HTTPS platform URL was recognised.' },
  fr: { ...es, aria:'Suite Intelligence ImportVerifier', heroTitle:'Une couche intelligente pour chaque produit.', heroLead:'Posez vos questions, comprenez l’état réglementaire, priorisez les changements et préparez les connexions aux canaux de vente depuis un seul endroit.', loading:'Préparation de l’intelligence de votre dernière analyse…', noAnalysis:'Créez votre première analyse pour activer ImportVerifier AI, Regulatory Twin et Impact Radar.', loadError:'La couche d’intelligence n’a pas pu être chargée. Le reste du tableau de bord reste disponible.', aiLead:'Assistant réglementaire contextuel fondé sur votre produit, les règles et les preuves enregistrées.', active:'ACTIF', productLabel:'Produit à consulter', defaultQuestion:'Que me manque-t-il pour avancer avec ce produit ?', questionPlaceholder:'Demandez ce qui manque, quoi demander au fournisseur ou pourquoi une règle s’applique…', asking:'Analyse…', ask:'Interroger ImportVerifier AI', aiError:'Impossible de consulter ImportVerifier AI.', aiDisclaimer:'Le contexte est reconstruit côté serveur à partir de votre analyse et de vos preuves enregistrées. Assistance indicative uniquement.', twinLead:'Jumeau réglementaire vivant du produit sélectionné.', live:'ACTIF', unclassified:'NON CLASSÉ', category:'Catégorie', confidence:'Confiance', evidenceAvailable:'Preuves disponibles', pendingReview:'En attente / à revoir', readinessDisclaimer:'Le readiness reflète l’état des preuves enregistrées par l’utilisateur et ne constitue pas une certification.', noClassification:'Aucune classification réglementaire disponible pour ce produit.', radarLead:'Priorise les changements officiels correspondant aux caractéristiques du produit sélectionné.', officialSources:'SOURCES OFFICIELLES', radar:'RADAR', action:'Action', review:'À revoir', information:'Information', context:'Contexte', officialSource:'Source officielle', radarNoMatch:'Des changements officiels sont enregistrés, mais aucun ne correspond encore aux mots-clés du produit.', radarNoEvents:'Aucun événement réglementaire officiel n’est encore enregistré ; ces points proviennent de l’analyse actuelle.', radarEmpty:'Aucun changement officiel pertinent ni impact notable pour ce produit.', connectLead:'Base d’intégration prête à importer les catalogues et actualiser leur état depuis les principales plateformes.', connectors:'CONNECTEURS', upcomingAuthorize:'Bientôt · Autoriser', platformPlaceholder:'Collez une URL HTTPS Shopify, Amazon ou Etsy pour détecter la plateforme', detect:'Détecter', platformDetected:'Plateforme détectée', authorizationPending:'L’autorisation sera activée lorsque l’intégration officielle sera configurée.', unknownPlatform:'Aucune URL HTTPS compatible reconnue.' },
  de: { ...es, aria:'ImportVerifier Intelligence Suite', heroTitle:'Eine intelligente Ebene für jedes Produkt.', heroLead:'Fragen stellen, regulatorischen Status verstehen, Änderungen priorisieren und Vertriebskanäle vorbereiten – an einem Ort.', loading:'Intelligenz für die letzte Analyse wird vorbereitet…', noAnalysis:'Erstellen Sie Ihre erste Analyse, um ImportVerifier AI, Regulatory Twin und Impact Radar zu aktivieren.', loadError:'Die Intelligence-Ebene konnte nicht geladen werden. Das übrige Dashboard bleibt verfügbar.', aiLead:'Kontextbezogener regulatorischer Assistent auf Basis Ihres Produkts, der Regeln und gespeicherten Nachweise.', active:'AKTIV', productLabel:'Produkt für die Anfrage', defaultQuestion:'Was fehlt, damit ich mit diesem Produkt fortfahren kann?', questionPlaceholder:'Fragen Sie, was fehlt, was vom Lieferanten anzufordern ist oder warum eine Vorschrift gilt…', asking:'Analyse…', ask:'ImportVerifier AI fragen', aiError:'ImportVerifier AI konnte nicht abgefragt werden.', aiDisclaimer:'Der Kontext wird serverseitig aus Ihrer Analyse und gespeicherten Nachweisen rekonstruiert. Nur orientierende Unterstützung.', twinLead:'Lebender regulatorischer Zwilling des ausgewählten Produkts.', live:'AKTIV', unclassified:'NICHT KLASSIFIZIERT', category:'Kategorie', confidence:'Konfidenz', evidenceAvailable:'Verfügbare Nachweise', pendingReview:'Ausstehend / prüfen', readinessDisclaimer:'Readiness spiegelt den vom Nutzer gespeicherten Nachweisstatus wider und ist keine Konformitätszertifizierung.', noClassification:'Für dieses Produkt ist keine regulatorische Klassifizierung verfügbar.', radarLead:'Priorisiert offizielle Änderungen, die zu den Merkmalen des ausgewählten Produkts passen.', officialSources:'OFFIZIELLE QUELLEN', radar:'RADAR', action:'Aktion', review:'Prüfen', information:'Information', context:'Kontext', officialSource:'Offizielle Quelle', radarNoMatch:'Offizielle Änderungen sind gespeichert, derzeit passt jedoch keine zu den Produkt-Schlüsselwörtern.', radarNoEvents:'Noch keine offiziellen regulatorischen Ereignisse gespeichert; diese Punkte stammen aus der aktuellen Produktanalyse.', radarEmpty:'Keine relevanten offiziellen Änderungen oder hervorgehobenen Auswirkungen für dieses Produkt.', connectLead:'Integrationsbasis zum Importieren von Katalogen und Aktualisieren ihres Status über wichtige Plattformen.', connectors:'KONNEKTOREN', upcomingAuthorize:'Demnächst · Autorisieren', platformPlaceholder:'HTTPS-URL von Shopify, Amazon oder Etsy einfügen, um die Plattform zu erkennen', detect:'Erkennen', platformDetected:'Plattform erkannt', authorizationPending:'Die Autorisierung wird aktiviert, sobald die offizielle Integration konfiguriert ist.', unknownPlatform:'Keine kompatible HTTPS-Plattform-URL erkannt.' },
  it: { ...es, aria:'Suite Intelligence ImportVerifier', heroTitle:'Un livello intelligente per ogni prodotto.', heroLead:'Fai domande, comprendi lo stato normativo, dai priorità ai cambiamenti e prepara i collegamenti ai canali di vendita da un unico punto.', loading:'Preparazione dell’intelligence dell’ultima analisi…', noAnalysis:'Crea la prima analisi per attivare ImportVerifier AI, Regulatory Twin e Impact Radar.', loadError:'Impossibile caricare il livello di intelligence. Il resto del pannello rimane disponibile.', aiLead:'Assistente normativo contestuale basato sul prodotto, sulle regole e sulle evidenze salvate.', active:'ATTIVO', productLabel:'Prodotto da consultare', defaultQuestion:'Cosa manca per poter procedere con questo prodotto?', questionPlaceholder:'Chiedi cosa manca, cosa richiedere al fornitore o perché si applica una norma…', asking:'Analisi…', ask:'Chiedi a ImportVerifier AI', aiError:'Impossibile consultare ImportVerifier AI.', aiDisclaimer:'Il contesto viene ricostruito sul server dalla tua analisi e dalle evidenze salvate. Assistenza orientativa soltanto.', twinLead:'Gemello normativo vivo del prodotto selezionato.', live:'VIVO', unclassified:'NON CLASSIFICATO', category:'Categoria', confidence:'Confidenza', evidenceAvailable:'Evidenze disponibili', pendingReview:'In attesa / revisione', readinessDisclaimer:'Il readiness riflette lo stato delle evidenze salvate dall’utente e non equivale a una certificazione.', noClassification:'Nessuna classificazione normativa disponibile per questo prodotto.', radarLead:'Dà priorità ai cambiamenti ufficiali coerenti con le caratteristiche del prodotto selezionato.', officialSources:'FONTI UFFICIALI', radar:'RADAR', action:'Azione', review:'Rivedere', information:'Informazione', context:'Contesto', officialSource:'Fonte ufficiale', radarNoMatch:'Sono presenti cambiamenti ufficiali, ma nessuno corrisponde ancora alle parole chiave del prodotto.', radarNoEvents:'Non sono ancora presenti eventi normativi ufficiali persistiti; questi punti derivano dall’analisi attuale.', radarEmpty:'Nessun cambiamento ufficiale rilevante o impatto evidenziato per questo prodotto.', connectLead:'Base di integrazione pronta per importare cataloghi e aggiornarne lo stato dalle principali piattaforme.', connectors:'CONNETTORI', upcomingAuthorize:'Prossimamente · Autorizza', platformPlaceholder:'Incolla un URL HTTPS Shopify, Amazon o Etsy per rilevare la piattaforma', detect:'Rileva', platformDetected:'Piattaforma rilevata', authorizationPending:'L’autorizzazione sarà attivata quando l’integrazione ufficiale sarà configurata.', unknownPlatform:'Nessun URL HTTPS compatibile riconosciuto.' },
  pt: { ...es, aria:'Suite de Inteligência ImportVerifier', heroTitle:'Uma camada inteligente para cada produto.', heroLead:'Pergunte, compreenda o estado regulatório, priorize alterações e prepare ligações aos canais de venda num único local.', loading:'A preparar a inteligência da última análise…', noAnalysis:'Crie a primeira análise para ativar ImportVerifier AI, Regulatory Twin e Impact Radar.', loadError:'Não foi possível carregar a camada de inteligência. O restante painel continua disponível.', aiLead:'Assistente regulatório contextual baseado no produto, regras e evidências guardadas.', active:'ATIVO', productLabel:'Produto para consultar', defaultQuestion:'O que falta para poder avançar com este produto?', questionPlaceholder:'Pergunte o que falta, o que pedir ao fornecedor ou porque se aplica uma regra…', asking:'A analisar…', ask:'Perguntar ao ImportVerifier AI', aiError:'Não foi possível consultar o ImportVerifier AI.', aiDisclaimer:'O contexto é reconstruído no servidor a partir da análise e das evidências guardadas. Assistência orientativa apenas.', twinLead:'Gémeo regulatório vivo do produto selecionado.', live:'ATIVO', unclassified:'NÃO CLASSIFICADO', category:'Categoria', confidence:'Confiança', evidenceAvailable:'Evidência disponível', pendingReview:'Pendente / rever', readinessDisclaimer:'O readiness reflete o estado da evidência guardada pelo utilizador e não equivale a certificação.', noClassification:'Não existe classificação regulatória disponível para este produto.', radarLead:'Prioriza alterações oficiais que correspondem às características do produto selecionado.', officialSources:'FONTES OFICIAIS', radar:'RADAR', action:'Ação', review:'Rever', information:'Informação', context:'Contexto', officialSource:'Fonte oficial', radarNoMatch:'Existem alterações oficiais guardadas, mas nenhuma corresponde ainda às palavras-chave do produto.', radarNoEvents:'Ainda não existem eventos regulatórios oficiais persistidos; estes pontos vêm da análise atual.', radarEmpty:'Sem alterações oficiais relevantes nem impactos destacados para este produto.', connectLead:'Base de integração pronta para importar catálogos e atualizar o respetivo estado nas principais plataformas.', connectors:'CONECTORES', upcomingAuthorize:'Brevemente · Autorizar', platformPlaceholder:'Cole um URL HTTPS Shopify, Amazon ou Etsy para detetar a plataforma', detect:'Detetar', platformDetected:'Plataforma detetada', authorizationPending:'A autorização será ativada quando a integração oficial estiver configurada.', unknownPlatform:'Não foi reconhecido um URL HTTPS compatível.' }
};
