import type { Language } from './landing-i18n';

export type ProductExtractionMessageKey =
  | 'origin'|'invalidFile'|'emptyFile'|'tooLarge'|'imageMime'|'mimeMismatch'|'documentMime'|'unsupportedFormat'
  | 'invalidPayload'|'readError'|'signIn'|'rateLimit'|'noProducts'|'freeOnlyDocument'|'backupRequired'|'interpretError'|'genericType';

type Copy = Record<ProductExtractionMessageKey, string>;
const es: Copy = {
  origin:'Origen no permitido.',invalidFile:'Archivo no válido.',emptyFile:'El archivo está vacío.',tooLarge:'El archivo supera el límite de 5 MB.',imageMime:'La imagen no tiene un tipo MIME compatible con su extensión.',mimeMismatch:'El tipo MIME declarado no coincide con el archivo recibido.',documentMime:'El tipo MIME no coincide con la extensión del documento.',unsupportedFormat:'Formato no compatible. Usa foto, PDF, Word o texto. CSV y Excel se procesan localmente.',invalidPayload:'El archivo está vacío o supera el límite de 5 MB.',readError:'No se ha podido leer el archivo.',signIn:'Inicia sesión para analizar documentos o imágenes.',rateLimit:'Hay demasiados documentos procesándose desde esta cuenta. Vuelve a intentarlo más tarde.',noProducts:'No se han encontrado productos identificables.',freeOnlyDocument:'Este documento no contiene una capa de texto utilizable en modo gratuito. Si es un PDF escaneado, exporta sus páginas como imágenes; los .doc antiguos deben guardarse como DOCX, ODT o PDF con texto.',backupRequired:'Este formato requiere temporalmente el proveedor documental de respaldo.',interpretError:'No se ha podido interpretar el documento.',genericType:'El tipo de archivo no es válido.'
};
export const productExtractionCopy: Record<Language, Copy> = {
  es,
  en:{...es,origin:'Origin not allowed.',invalidFile:'Invalid file.',emptyFile:'The file is empty.',tooLarge:'The file exceeds the 5 MB limit.',imageMime:'The image MIME type is not compatible with its extension.',mimeMismatch:'The declared MIME type does not match the received file.',documentMime:'The MIME type does not match the document extension.',unsupportedFormat:'Unsupported format. Use a photo, PDF, Word document or text. CSV and Excel are processed locally.',invalidPayload:'The file is empty or exceeds the 5 MB limit.',readError:'The file could not be read.',signIn:'Sign in to analyse documents or images.',rateLimit:'Too many documents are being processed from this account. Try again later.',noProducts:'No identifiable products were found.',freeOnlyDocument:'This document has no usable text layer in free mode. For a scanned PDF, export its pages as images; legacy .doc files must be saved as DOCX, ODT or a PDF with text.',backupRequired:'This format temporarily requires the backup document provider.',interpretError:'The document could not be interpreted.',genericType:'The file type is not valid.'},
  fr:{...es,origin:'Origine non autorisée.',invalidFile:'Fichier non valide.',emptyFile:'Le fichier est vide.',tooLarge:'Le fichier dépasse la limite de 5 Mo.',imageMime:'Le type MIME de l’image n’est pas compatible avec son extension.',mimeMismatch:'Le type MIME déclaré ne correspond pas au fichier reçu.',documentMime:'Le type MIME ne correspond pas à l’extension du document.',unsupportedFormat:'Format non pris en charge. Utilisez une photo, un PDF, un document Word ou du texte. Les fichiers CSV et Excel sont traités localement.',invalidPayload:'Le fichier est vide ou dépasse la limite de 5 Mo.',readError:'Impossible de lire le fichier.',signIn:'Connectez-vous pour analyser des documents ou des images.',rateLimit:'Trop de documents sont en cours de traitement pour ce compte. Réessayez plus tard.',noProducts:'Aucun produit identifiable n’a été trouvé.',freeOnlyDocument:'Ce document ne contient pas de couche de texte exploitable en mode gratuit. Pour un PDF numérisé, exportez ses pages en images ; les anciens fichiers .doc doivent être enregistrés en DOCX, ODT ou PDF avec texte.',backupRequired:'Ce format nécessite temporairement le fournisseur documentaire de secours.',interpretError:'Impossible d’interpréter le document.',genericType:'Le type de fichier n’est pas valide.'},
  de:{...es,origin:'Ursprung nicht zulässig.',invalidFile:'Ungültige Datei.',emptyFile:'Die Datei ist leer.',tooLarge:'Die Datei überschreitet das Limit von 5 MB.',imageMime:'Der MIME-Typ des Bildes passt nicht zur Dateiendung.',mimeMismatch:'Der angegebene MIME-Typ stimmt nicht mit der empfangenen Datei überein.',documentMime:'Der MIME-Typ passt nicht zur Dokumentendung.',unsupportedFormat:'Nicht unterstütztes Format. Verwende Foto, PDF, Word oder Text. CSV und Excel werden lokal verarbeitet.',invalidPayload:'Die Datei ist leer oder überschreitet das Limit von 5 MB.',readError:'Die Datei konnte nicht gelesen werden.',signIn:'Melde dich an, um Dokumente oder Bilder zu analysieren.',rateLimit:'Für dieses Konto werden zu viele Dokumente verarbeitet. Versuche es später erneut.',noProducts:'Es wurden keine identifizierbaren Produkte gefunden.',freeOnlyDocument:'Dieses Dokument enthält im kostenlosen Modus keine nutzbare Textebene. Exportiere bei einem gescannten PDF die Seiten als Bilder; ältere .doc-Dateien müssen als DOCX, ODT oder PDF mit Text gespeichert werden.',backupRequired:'Dieses Format benötigt vorübergehend den Dokument-Backupanbieter.',interpretError:'Das Dokument konnte nicht interpretiert werden.',genericType:'Der Dateityp ist ungültig.'},
  it:{...es,origin:'Origine non consentita.',invalidFile:'File non valido.',emptyFile:'Il file è vuoto.',tooLarge:'Il file supera il limite di 5 MB.',imageMime:'Il tipo MIME dell’immagine non è compatibile con la sua estensione.',mimeMismatch:'Il tipo MIME dichiarato non corrisponde al file ricevuto.',documentMime:'Il tipo MIME non corrisponde all’estensione del documento.',unsupportedFormat:'Formato non supportato. Usa una foto, un PDF, un documento Word o testo. CSV ed Excel vengono elaborati localmente.',invalidPayload:'Il file è vuoto o supera il limite di 5 MB.',readError:'Impossibile leggere il file.',signIn:'Accedi per analizzare documenti o immagini.',rateLimit:'Da questo account sono in elaborazione troppi documenti. Riprova più tardi.',noProducts:'Non sono stati trovati prodotti identificabili.',freeOnlyDocument:'Questo documento non contiene un livello di testo utilizzabile in modalità gratuita. Se è un PDF scansionato, esporta le pagine come immagini; i vecchi file .doc devono essere salvati come DOCX, ODT o PDF con testo.',backupRequired:'Questo formato richiede temporaneamente il provider documentale di backup.',interpretError:'Impossibile interpretare il documento.',genericType:'Il tipo di file non è valido.'},
  pt:{...es,origin:'Origem não permitida.',invalidFile:'Ficheiro inválido.',emptyFile:'O ficheiro está vazio.',tooLarge:'O ficheiro excede o limite de 5 MB.',imageMime:'O tipo MIME da imagem não é compatível com a respetiva extensão.',mimeMismatch:'O tipo MIME declarado não corresponde ao ficheiro recebido.',documentMime:'O tipo MIME não corresponde à extensão do documento.',unsupportedFormat:'Formato não suportado. Utilize uma foto, PDF, documento Word ou texto. CSV e Excel são processados localmente.',invalidPayload:'O ficheiro está vazio ou excede o limite de 5 MB.',readError:'Não foi possível ler o ficheiro.',signIn:'Inicie sessão para analisar documentos ou imagens.',rateLimit:'Há demasiados documentos a ser processados nesta conta. Tente novamente mais tarde.',noProducts:'Não foram encontrados produtos identificáveis.',freeOnlyDocument:'Este documento não contém uma camada de texto utilizável no modo gratuito. Se for um PDF digitalizado, exporte as páginas como imagens; ficheiros .doc antigos devem ser guardados como DOCX, ODT ou PDF com texto.',backupRequired:'Este formato requer temporariamente o fornecedor documental de reserva.',interpretError:'Não foi possível interpretar o documento.',genericType:'O tipo de ficheiro não é válido.'}
};

export function productExtractionText(language: Language, key: ProductExtractionMessageKey): string {
  return productExtractionCopy[language][key];
}
